"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import {
  AlertTriangle, CheckCircle2, CircleOff, Clock3, Cpu, KeyRound,
  LoaderCircle, RefreshCw, Save, Search, Server, ShieldCheck, Star,
} from "lucide-react";

import { useToast } from "@/components/ui/Toast";
import { platformService } from "@/services/platformApi";
import type { PlatformAIModel, PlatformAIModelOperations, PlatformAIModelSyncRun, PlatformAIProvider } from "@/types/platform";
import styles from "./page.module.css";

const number = new Intl.NumberFormat("pt-BR");
const dateTime = (value:string|null) => value ? new Date(value).toLocaleString("pt-BR") : "Nunca";

function ProviderCard({provider,canEdit,onChange}:{provider:PlatformAIProvider;canEdit:boolean;onChange:(value:PlatformAIProvider)=>void}) {
  const [saving,setSaving]=useState(false);
  const {showToast}=useToast();
  const update=async(payload:Parameters<typeof platformService.updateAIProvider>[1])=>{
    setSaving(true);
    try{onChange(await platformService.updateAIProvider(provider.id,payload));showToast("Provedor atualizado.","success");}
    catch{showToast("Não foi possível atualizar o provedor.","error");}
    finally{setSaving(false);}
  };
  const healthy=provider.last_health_status==="healthy";
  return <article className={styles.providerCard}>
    <header><span className={healthy?styles.providerHealthy:styles.providerNeutral}><Server size={20}/></span><div><h3>{provider.display_name}</h3><code>{provider.provider}</code></div>{provider.is_default&&<b><Star size={12}/>Padrão</b>}</header>
    <div className={styles.providerFacts}><span><KeyRound size={14}/><small>Credencial</small><strong className={provider.credential_configured?styles.goodText:styles.badText}>{provider.credential_configured?"Configurada":"Ausente"}</strong></span><span><ShieldCheck size={14}/><small>Saúde</small><strong>{provider.health_status_display}</strong></span><span><Clock3 size={14}/><small>Última verificação</small><strong>{dateTime(provider.last_health_check_at)}</strong></span></div>
    {canEdit&&<footer><label className={styles.switch}><input type="checkbox" checked={provider.is_enabled} disabled={saving||provider.is_default} onChange={event=>void update({is_enabled:event.target.checked})}/><span/></label><em>{provider.is_enabled?"Habilitado":"Desabilitado"}</em>{!provider.is_default&&<button disabled={saving||!provider.is_enabled} onClick={()=>void update({is_default:true,is_enabled:true})}><Star size={14}/>Definir padrão</button>}{saving&&<LoaderCircle className={styles.spin} size={15}/>}</footer>}
  </article>;
}

function ModelRow({model,canEdit,onChange}:{model:PlatformAIModel;canEdit:boolean;onChange:(value:PlatformAIModel)=>void}) {
  const [priority,setPriority]=useState(String(model.priority));const [saving,setSaving]=useState(false);const {showToast}=useToast();
  const update=async(payload:Parameters<typeof platformService.updateAIModel>[1])=>{setSaving(true);try{const next=await platformService.updateAIModel(model.id,payload);onChange(next);setPriority(String(next.priority));showToast("Modelo atualizado.","success");}catch{showToast("Não foi possível atualizar o modelo.","error");}finally{setSaving(false);}};
  return <tr><td><div className={styles.modelName}><span><Cpu size={16}/></span><div><strong>{model.display_name}</strong><code>{model.external_id}</code></div></div></td><td>{model.provider_name}</td><td><span className={`${styles.modelBadge} ${model.is_free?styles.freeBadge:styles.paidBadge}`}>{model.is_free?"Gratuito":"Pago"}</span></td><td><span className={`${styles.modelBadge} ${model.is_available?styles.availableBadge:styles.unavailableBadge}`}>{model.is_available?"Disponível":"Indisponível"}</span></td><td>{model.endpoint_type_display}<small className={styles.tableNote}>{model.context_window?`${number.format(model.context_window)} tokens`:"Contexto não informado"}</small></td><td>{canEdit?<div className={styles.modelControls}><label className={styles.switch}><input type="checkbox" checked={model.is_enabled} disabled={saving||!model.is_available||model.is_primary} onChange={event=>void update({is_enabled:event.target.checked})}/><span/></label><button className={model.is_primary?styles.primaryButton:styles.secondaryButton} disabled={saving||!model.is_available} onClick={()=>void update({is_primary:true,is_enabled:true})}><Star size={13}/>{model.is_primary?"Principal":"Usar como principal"}</button><input type="number" min="1" max="9999" value={priority} onChange={event=>setPriority(event.target.value)} aria-label={`Prioridade de ${model.display_name}`}/><button className={styles.savePriority} disabled={saving||Number(priority)===model.priority} onClick={()=>void update({priority:Math.max(Number(priority)||100,1)})}>{saving?<LoaderCircle className={styles.spin} size={14}/>:<Save size={14}/>}</button></div>:<span className={styles.readOnly}>Somente leitura</span>}</td></tr>;
}

function SyncHistory({runs}:{runs:PlatformAIModelSyncRun[]}) {return <div className={styles.syncHistory}>{runs.slice(0,6).map(run=><div key={run.id}><span className={run.status==="success"?styles.successIcon:run.status==="failure"?styles.failedIcon:styles.blockedIcon}>{run.status==="success"?<CheckCircle2 size={17}/>:run.status==="failure"?<CircleOff size={17}/>:<LoaderCircle className={styles.spin} size={17}/>}</span><p><strong>{run.provider_name}</strong><small>{run.trigger_display} · {dateTime(run.started_at)}</small></p><b>{run.status_display}</b><em>{run.free_models_found} gratuitos · {run.models_created} novos</em></div>)}{!runs.length&&<div className={styles.empty}>Nenhuma sincronização registrada.</div>}</div>}

export function AIModelManagement({canEdit,operations}:{canEdit:boolean;operations:PlatformAIModelOperations}) {
  const [providers,setProviders]=useState<PlatformAIProvider[]>([]);const [models,setModels]=useState<PlatformAIModel[]>([]);const [runs,setRuns]=useState<PlatformAIModelSyncRun[]>([]);const [loading,setLoading]=useState(true);const [syncing,setSyncing]=useState(false);const [error,setError]=useState("");const [search,setSearch]=useState("");const [showPaid,setShowPaid]=useState(false);const {showToast}=useToast();
  const load=useCallback(async()=>{setError("");try{const [nextProviders,nextModels,nextRuns]=await Promise.all([platformService.aiProviders(),platformService.aiModels(),platformService.aiModelSyncRuns()]);setProviders(nextProviders);setModels(nextModels);setRuns(nextRuns);}catch{setError("Não foi possível carregar o catálogo de IA.");}finally{setLoading(false);}},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  const filtered=useMemo(()=>{const query=search.trim().toLocaleLowerCase("pt-BR");return models.filter(model=>(showPaid||model.is_free)&&(!query||model.display_name.toLocaleLowerCase("pt-BR").includes(query)||model.external_id.toLocaleLowerCase("pt-BR").includes(query)||model.provider_name.toLocaleLowerCase("pt-BR").includes(query)));},[models,search,showPaid]);
  const sync=async()=>{setSyncing(true);try{await platformService.syncAIModels();showToast("Sincronização adicionada à fila.","success");setTimeout(()=>void load(),1800);}catch{showToast("Não foi possível iniciar a sincronização.","error");}finally{setSyncing(false);}};
  const changeProvider=(next:PlatformAIProvider)=>setProviders(current=>current.map(item=>item.id===next.id?next:next.is_default?{...item,is_default:false}:item));
  const changeModel=(next:PlatformAIModel)=>setModels(current=>current.map(item=>item.id===next.id?next:next.is_primary&&item.provider===next.provider?{...item,is_primary:false}:item));
  if(loading)return <section className={`${styles.panel} ${styles.catalogLoading}`}><LoaderCircle className={styles.spin}/><span>Carregando catálogo de modelos…</span></section>;
  return <><section className={styles.operationSummary}>{operations.alerts.map(alert=><div key={alert.code} data-severity={alert.severity}><AlertTriangle size={17}/><span>{alert.message}</span></div>)}<div className={styles.operationStats}><article><small>Modelos gratuitos ativos</small><strong>{operations.catalog.enabled_free_models}</strong><span>de {operations.catalog.available_free_models} disponíveis</span></article><article><small>Uso de fallback</small><strong>{operations.routing.fallback_rate.toLocaleString("pt-BR")}%</strong><span>{operations.routing.fallback_answers} respostas no período</span></article><article><small>Última sincronização válida</small><strong>{operations.catalog.is_stale?"Desatualizada":"Em dia"}</strong><span>{dateTime(operations.catalog.last_success_at)}</span></article><article><small>Fallback pago</small><strong>{operations.routing.paid_fallback_allowed?"Permitido":"Bloqueado"}</strong><span>Controle global de custo</span></article></div></section>
    <section className={styles.panel}><header className={styles.panelHeader}><div><small>Infraestrutura de IA</small><h2>Provedores e credenciais</h2></div>{canEdit&&<button className={styles.syncButton} onClick={()=>void sync()} disabled={syncing}>{syncing?<LoaderCircle className={styles.spin} size={15}/>:<RefreshCw size={15}/>}Sincronizar modelos</button>}</header>{error&&<div className={styles.catalogError}><AlertTriangle size={17}/>{error}</div>}<div className={styles.providerGrid}>{providers.map(provider=><ProviderCard key={provider.id} provider={provider} canEdit={canEdit} onChange={changeProvider}/>)}</div></section>
    <section className={styles.panel}><header className={styles.panelHeader}><div><small>Roteamento e fallback</small><h2>Catálogo de modelos</h2></div><div className={styles.filters}><label><Search size={16}/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Buscar modelo ou provedor…"/></label><button className={showPaid?styles.filterActive:""} onClick={()=>setShowPaid(value=>!value)}>{showPaid?"Ocultar pagos":"Exibir pagos"}</button></div></header><div className={styles.tableWrap}><table className={styles.modelTable}><thead><tr><th>Modelo</th><th>Provedor</th><th>Custo</th><th>Status</th><th>API e contexto</th><th>Roteamento</th></tr></thead><tbody>{filtered.map(model=><ModelRow key={model.id} model={model} canEdit={canEdit} onChange={changeModel}/>)}</tbody></table>{!filtered.length&&<div className={styles.empty}>Nenhum modelo encontrado. Execute a sincronização do catálogo.</div>}</div></section>
    <section className={styles.panel}><header className={styles.panelHeader}><div><small>Uso por modelo</small><h2>Roteamento no período</h2></div><span className={styles.privacy}>Sem conteúdo das conversas</span></header><div className={styles.tableWrap}><table className={styles.usageTable}><thead><tr><th>Modelo</th><th>Provedor</th><th>Respostas</th><th>Tokens</th><th>Latência média</th><th>Fallbacks</th></tr></thead><tbody>{operations.model_usage.map(row=><tr key={`${row.provider}-${row.model}`}><td><code>{row.model}</code></td><td>{row.provider}</td><td>{number.format(row.answers)}</td><td>{number.format(row.input_tokens+row.output_tokens)}</td><td>{number.format(row.average_latency_ms)} ms</td><td>{row.fallback_answers} respostas · {row.fallback_total} tentativas</td></tr>)}</tbody></table>{!operations.model_usage.length&&<div className={styles.empty}>Nenhum uso de modelo registrado no período.</div>}</div></section>
    <section className={styles.panel}><header className={styles.panelHeader}><div><small>Auditoria do catálogo</small><h2>Sincronizações recentes</h2></div><span className={styles.privacy}>Últimas 6 execuções</span></header><SyncHistory runs={runs}/></section></>;
}
