"use client";

import { useEffect, useMemo, useState } from "react";
import {
  AlertTriangle, Bot, Building2, CheckCircle2, CircleDollarSign, Gauge,
  LoaderCircle, MessageSquareText, Save, Search, ShieldAlert, Sparkles,
  ThumbsUp, XCircle,
} from "lucide-react";

import { PLATFORM_STAFF, platformService } from "@/services/platformApi";
import type { PlatformAIDashboard, PlatformAIOrganization, PlatformStaff } from "@/types/platform";
import styles from "./page.module.css";

const integer=new Intl.NumberFormat("pt-BR");
const usd=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"USD",minimumFractionDigits:2,maximumFractionDigits:4});

function Metric({label,value,note,Icon,tone}:{label:string;value:string;note:string;Icon:typeof Bot;tone:string}){return <article className={`${styles.metric} ${styles[tone]}`}><span><Icon size={24}/></span><div><small>{label}</small><strong>{value}</strong><p>{note}</p></div></article>}

function OrganizationRow({item,canEdit,onSaved}:{item:PlatformAIOrganization;canEdit:boolean;onSaved:(data:{enabled:boolean;limit:number|null})=>void}){
  const [enabled,setEnabled]=useState(item.enabled);const [limit,setLimit]=useState(String(item.limit??""));const [saving,setSaving]=useState(false);const [saved,setSaved]=useState(false);const [error,setError]=useState("");
  const save=async()=>{setSaving(true);setError("");try{const data=await platformService.updateOrganizationAI(item.id,{enabled,limit:Math.max(Number(limit)||0,0)});onSaved(data);setSaved(true);setTimeout(()=>setSaved(false),1800);}catch{setError("Falha ao salvar");}finally{setSaving(false);}};
  const percentage=item.limit?Math.min(item.used/item.limit*100,100):0;
  return <tr><td><div className={styles.orgName}><span><Building2 size={17}/></span><div><strong>{item.name}</strong><small>{item.plan}</small></div></div></td><td><span className={`${styles.status} ${enabled?styles.on:styles.off}`}>{enabled?"Ativa":"Bloqueada"}</span></td><td><div className={styles.usage}><div><strong>{integer.format(item.used)}</strong><small>de {item.limit==null?"∞":integer.format(item.limit)}</small></div><span><i style={{width:`${percentage}%`}}/></span></div></td><td>{integer.format(item.users)}</td><td>{integer.format(item.input_tokens+item.output_tokens)}</td><td>{usd.format(item.cost_usd)}</td><td>{canEdit?<div className={styles.controls}><label className={styles.switch} title={enabled?"Desativar IA":"Ativar IA"}><input type="checkbox" checked={enabled} onChange={event=>setEnabled(event.target.checked)}/><span/></label><input type="number" min="0" max="100000" value={limit} onChange={event=>setLimit(event.target.value)} aria-label={`Limite de ${item.name}`}/><button onClick={save} disabled={saving}>{saving?<LoaderCircle className={styles.spin} size={16}/>:saved?<CheckCircle2 size={16}/>:<Save size={16}/>}</button>{error&&<small className={styles.rowError}>{error}</small>}</div>:<span className={styles.readOnly}>Somente leitura</span>}</td></tr>;
}

export default function PlatformAIPage(){
  const [data,setData]=useState<PlatformAIDashboard|null>(null);const [error,setError]=useState("");const [search,setSearch]=useState("");const [onlyIssues,setOnlyIssues]=useState(false);const [staff]=useState<PlatformStaff|null>(()=>{if(typeof window==="undefined")return null;try{const raw=localStorage.getItem(PLATFORM_STAFF);return raw?JSON.parse(raw):null;}catch{return null;}});
  useEffect(()=>{platformService.aiDashboard().then(setData).catch(()=>setError("Não foi possível carregar os indicadores da IA."));},[]);
  const organizations=useMemo(()=>{const query=search.trim().toLocaleLowerCase("pt-BR");return(data?.organizations??[]).filter(item=>(!query||item.name.toLocaleLowerCase("pt-BR").includes(query)||item.plan.toLocaleLowerCase("pt-BR").includes(query))&&(!onlyIssues||!item.enabled||(item.limit!=null&&item.used>=item.limit)));},[data,search,onlyIssues]);
  const canEdit=["platform_owner","platform_admin"].includes(staff?.role??"");
  const updateRow=(id:string,next:{enabled:boolean;limit:number|null})=>setData(current=>current?{...current,organizations:current.organizations.map(item=>item.id===id?{...item,...next,remaining:next.limit==null?null:Math.max(next.limit-item.used,0)}:item)}:current);
  if(!data&&!error)return <div className={styles.loading}><LoaderCircle className={styles.spin}/><span>Carregando operação da IA…</span></div>;
  if(error)return <div className={styles.pageError}><AlertTriangle size={20}/>{error}</div>;
  if(!data)return null;
  const totalTokens=data.metrics.input_tokens+data.metrics.output_tokens;const maxSubject=Math.max(...data.subjects.map(item=>item.total),1);
  return <div className={styles.page}><header className={styles.header}><div><span><Sparkles size={15}/>OPERAÇÃO DE INTELIGÊNCIA ARTIFICIAL</span><h1>Assistente Rural IA</h1><p>Monitore adoção, segurança, qualidade e consumo por organização sem acessar o conteúdo das conversas.</p></div><div className={styles.period}>Período: {new Date(`${data.period.start}T00:00:00`).toLocaleDateString("pt-BR")} a {new Date(`${data.period.end}T00:00:00`).toLocaleDateString("pt-BR")}</div></header>
    <section className={styles.metrics}><Metric label="Perguntas no mês" value={integer.format(data.metrics.questions)} note={`${integer.format(data.metrics.active_users)} usuários ativos`} Icon={MessageSquareText} tone="green"/><Metric label="Tokens processados" value={integer.format(totalTokens)} note={`${integer.format(data.metrics.completed_answers)} respostas concluídas`} Icon={Gauge} tone="blue"/><Metric label="Custo estimado" value={usd.format(data.metrics.cost_usd)} note={`${integer.format(data.metrics.active_organizations)} organizações utilizaram`} Icon={CircleDollarSign} tone="orange"/><Metric label="Respostas úteis" value={`${data.metrics.helpful_rate.toLocaleString("pt-BR")}%`} note={`${data.metrics.helpful} de ${data.metrics.feedback_total} avaliações`} Icon={ThumbsUp} tone="purple"/></section>
    <section className={styles.insights}><article><header><div><small>Distribuição</small><h2>Assuntos das conversas</h2></div><Bot size={21}/></header><div className={styles.subjects}>{data.subjects.length?data.subjects.map(item=><div key={item.subject}><div><span>{item.label}</span><strong>{item.total}</strong></div><span><i style={{width:`${item.total/maxSubject*100}%`}}/></span></div>):<p>Nenhuma conversa iniciada no período.</p>}</div></article><article><header><div><small>Segurança e estabilidade</small><h2>Ocorrências do período</h2></div><ShieldAlert size={21}/></header><div className={styles.health}><div><span className={styles.blockedIcon}><ShieldAlert size={20}/></span><p><small>Bloqueadas</small><strong>{data.metrics.blocked}</strong></p></div><div><span className={styles.failedIcon}><XCircle size={20}/></span><p><small>Falhas técnicas</small><strong>{data.metrics.failed}</strong></p></div><div><span className={styles.successIcon}><CheckCircle2 size={20}/></span><p><small>Concluídas</small><strong>{data.metrics.completed_answers}</strong></p></div></div></article></section>
    <section className={styles.panel}><header className={styles.panelHeader}><div><small>Franquias e acesso</small><h2>Consumo por organização</h2></div><div className={styles.filters}><label><Search size={16}/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Buscar organização ou plano…"/></label><button className={onlyIssues?styles.filterActive:""} onClick={()=>setOnlyIssues(value=>!value)}><AlertTriangle size={15}/>Somente atenção</button></div></header><div className={styles.tableWrap}><table><thead><tr><th>Organização</th><th>Status</th><th>Franquia</th><th>Usuários</th><th>Tokens</th><th>Custo</th><th>Controle</th></tr></thead><tbody>{organizations.map(item=><OrganizationRow key={`${item.id}-${item.enabled}-${item.limit}`} item={item} canEdit={canEdit} onSaved={next=>updateRow(item.id,next)}/>)}</tbody></table>{organizations.length===0&&<div className={styles.empty}>Nenhuma organização encontrada.</div>}</div></section>
    <section className={styles.panel}><header className={styles.panelHeader}><div><small>Metadados protegidos</small><h2>Bloqueios e falhas recentes</h2></div><span className={styles.privacy}>Conteúdo das conversas não é exibido</span></header><div className={styles.incidents}>{data.incidents.length?data.incidents.map(item=><div key={item.id}><span className={item.status==="blocked"?styles.blockedIcon:styles.failedIcon}>{item.status==="blocked"?<ShieldAlert size={18}/>:<XCircle size={18}/>}</span><p><strong>{item.organization}</strong><small>{item.subject} · {item.role}</small></p><b>{item.status==="blocked"?"Bloqueada":"Falha"}</b><time>{new Date(item.created_at).toLocaleString("pt-BR")}</time></div>):<div className={styles.empty}><CheckCircle2 size={20}/>Nenhuma ocorrência registrada no período.</div>}</div></section>
  </div>;
}
