/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardUsuariosRouteImport } from './routes/dashboard.usuarios'
import { Route as DashboardRebanhoRouteImport } from './routes/dashboard.rebanho'
import { Route as DashboardLavouraRouteImport } from './routes/dashboard.lavoura'
import { Route as DashboardFinanceiroRouteImport } from './routes/dashboard.financeiro'
import { Route as DashboardEstoqueRouteImport } from './routes/dashboard.estoque'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsuariosRoute = DashboardUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRebanhoRoute = DashboardRebanhoRouteImport.update({
  id: '/rebanho',
  path: '/rebanho',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLavouraRoute = DashboardLavouraRouteImport.update({
  id: '/lavoura',
  path: '/lavoura',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFinanceiroRoute = DashboardFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEstoqueRoute = DashboardEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/estoque': typeof DashboardEstoqueRoute
  '/dashboard/financeiro': typeof DashboardFinanceiroRoute
  '/dashboard/lavoura': typeof DashboardLavouraRoute
  '/dashboard/rebanho': typeof DashboardRebanhoRoute
  '/dashboard/usuarios': typeof DashboardUsuariosRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/estoque': typeof DashboardEstoqueRoute
  '/dashboard/financeiro': typeof DashboardFinanceiroRoute
  '/dashboard/lavoura': typeof DashboardLavouraRoute
  '/dashboard/rebanho': typeof DashboardRebanhoRoute
  '/dashboard/usuarios': typeof DashboardUsuariosRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/estoque': typeof DashboardEstoqueRoute
  '/dashboard/financeiro': typeof DashboardFinanceiroRoute
  '/dashboard/lavoura': typeof DashboardLavouraRoute
  '/dashboard/rebanho': typeof DashboardRebanhoRoute
  '/dashboard/usuarios': typeof DashboardUsuariosRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/estoque'
    | '/dashboard/financeiro'
    | '/dashboard/lavoura'
    | '/dashboard/rebanho'
    | '/dashboard/usuarios'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/estoque'
    | '/dashboard/financeiro'
    | '/dashboard/lavoura'
    | '/dashboard/rebanho'
    | '/dashboard/usuarios'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/estoque'
    | '/dashboard/financeiro'
    | '/dashboard/lavoura'
    | '/dashboard/rebanho'
    | '/dashboard/usuarios'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/usuarios': {
      id: '/dashboard/usuarios'
      path: '/usuarios'
      fullPath: '/dashboard/usuarios'
      preLoaderRoute: typeof DashboardUsuariosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/rebanho': {
      id: '/dashboard/rebanho'
      path: '/rebanho'
      fullPath: '/dashboard/rebanho'
      preLoaderRoute: typeof DashboardRebanhoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/lavoura': {
      id: '/dashboard/lavoura'
      path: '/lavoura'
      fullPath: '/dashboard/lavoura'
      preLoaderRoute: typeof DashboardLavouraRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/financeiro': {
      id: '/dashboard/financeiro'
      path: '/financeiro'
      fullPath: '/dashboard/financeiro'
      preLoaderRoute: typeof DashboardFinanceiroRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/estoque': {
      id: '/dashboard/estoque'
      path: '/estoque'
      fullPath: '/dashboard/estoque'
      preLoaderRoute: typeof DashboardEstoqueRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardEstoqueRoute: typeof DashboardEstoqueRoute
  DashboardFinanceiroRoute: typeof DashboardFinanceiroRoute
  DashboardLavouraRoute: typeof DashboardLavouraRoute
  DashboardRebanhoRoute: typeof DashboardRebanhoRoute
  DashboardUsuariosRoute: typeof DashboardUsuariosRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardEstoqueRoute: DashboardEstoqueRoute,
  DashboardFinanceiroRoute: DashboardFinanceiroRoute,
  DashboardLavouraRoute: DashboardLavouraRoute,
  DashboardRebanhoRoute: DashboardRebanhoRoute,
  DashboardUsuariosRoute: DashboardUsuariosRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
