"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { CircleDollarSign, ClockAlert, FileText, Plus, TrendingUp } from "lucide-react";
import { useToast } from "@/components/ui/Toast";
import { platformService } from "@/services/platformApi";
import type { PlatformFinanceDashboard, PlatformInvoicePage, PlatformOrganization } from "@/types/platform";

const money=(value:string)=>Number(value).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});

export default function PlatformFinancePage(){
 const {showToast}=useToast(); const [dashboard,setDashboard]=useState<PlatformFinanceDashboard|null>(null); const [invoices,setInvoices]=useState<PlatformInvoicePage|null>(null); const [organizations,setOrganizations]=useState<PlatformOrganization[]>([]); const [showForm,setShowForm]=useState(false); const [form,setForm]=useState({organization_id:"",due_date:"",description:"Mensalidade AgroManage",amount:""});
 const load=useCallback(()=>{Promise.all([platformService.financeDashboard(),platformService.invoices({page_size:100}),platformService.organizations({page_size:100,is_active:true})]).then(([d,i,o])=>{setDashboard(d);setInvoices(i);setOrganizations(o.results);}).catch(()=>showToast("Não foi possível carregar o financeiro.","error"));},[showToast]);
 useEffect(()=>{load();},[load]);
 const create=async(e:FormEvent)=>{e.preventDefault();try{await platformService.createInvoice(form);showToast("Fatura criada.","success");setShowForm(false);load();}catch{showToast("Não foi possível criar a fatura.","error");}};
 const pay=async(id:string,due:string)=>{const amount=window.prompt("Valor recebido",due);if(!amount)return;try{await platformService.recordInvoicePayment(id,amount,"manual");showToast("Pagamento registrado.","success");load();}catch{showToast("Não foi possível registrar o pagamento.","error");}};
 const metrics=dashboard?[{label:"MRR",value:money(dashboard.mrr),icon:TrendingUp},{label:"ARR",value:money(dashboard.arr),icon:CircleDollarSign},{label:"Recebido no mês",value:money(dashboard.received_month),icon:CircleDollarSign},{label:"Em aberto",value:money(dashboard.outstanding),icon:ClockAlert}]:[];
 return <><div className="d-flex justify-content-between align-items-end mb-4"><div><div className="platform-label mb-2">Receita da plataforma</div><h1 className="h2 fw-bold mb-1">Financeiro SaaS</h1><p className="text-muted mb-0">Faturas, recebimentos e recorrência comercial.</p></div><button className="btn btn-dark d-flex gap-2" onClick={()=>setShowForm(!showForm)}><Plus size={17}/>Nova fatura</button></div>
 {showForm&&<form className="platform-card p-4 mb-4" onSubmit={create}><h2 className="h5 fw-bold mb-3">Emitir fatura manual</h2><div className="row g-3"><div className="col-md-4"><label className="form-label">Organização</label><select className="form-select" required value={form.organization_id} onChange={e=>setForm({...form,organization_id:e.target.value})}><option value="">Selecione</option>{organizations.map(o=><option value={o.id} key={o.id}>{o.name}</option>)}</select></div><div className="col-md-3"><label className="form-label">Vencimento</label><input type="date" className="form-control" required value={form.due_date} onChange={e=>setForm({...form,due_date:e.target.value})}/></div><div className="col-md-2"><label className="form-label">Valor</label><input type="number" step="0.01" min="0.01" className="form-control" required value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></div><div className="col-md-3"><label className="form-label">Descrição</label><input className="form-control" required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div></div><button className="btn btn-success mt-3">Emitir fatura</button></form>}
 <div className="row g-3 mb-4">{metrics.map(m=><div className="col-sm-6 col-xl-3" key={m.label}><div className="platform-card platform-metric"><div className="d-flex justify-content-between"><div className="platform-label">{m.label}</div><div className="platform-icon"><m.icon size={19}/></div></div><div className="fs-3 fw-bold mt-3">{m.value}</div></div></div>)}</div>
 <div className="platform-card overflow-hidden"><div className="p-4 border-bottom d-flex justify-content-between"><div><h2 className="h5 fw-bold mb-1">Faturas</h2><div className="text-muted small">{dashboard?.overdue_invoices??0} vencidas · {dashboard?.open_invoices??0} em aberto</div></div><FileText className="text-muted"/></div><div className="table-responsive"><table className="table platform-table mb-0"><thead><tr><th>Número</th><th>Organização</th><th>Plano</th><th>Vencimento</th><th>Total</th><th>Em aberto</th><th>Status</th><th/></tr></thead><tbody>{invoices?.results.map(i=><tr key={i.id}><td className="fw-semibold">{i.number}</td><td>{i.organization_name}</td><td>{i.plan_name}</td><td>{new Date(`${i.due_date}T12:00:00`).toLocaleDateString("pt-BR")}</td><td>{money(i.total)}</td><td>{money(i.amount_due)}</td><td><span className={`platform-status ${i.status==="paid"?"active":"suspended"}`}>{i.status_display}</span></td><td>{!(["paid","void"].includes(i.status))&&<button className="btn btn-outline-success btn-sm" onClick={()=>pay(i.id,i.amount_due)}>Registrar pagamento</button>}</td></tr>)}</tbody></table></div></div></>;
}
