# Generated by Django 5.2.13 on 2026-04-25 02:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150)),
                ('contato_principal', models.CharField(blank=True, max_length=150)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cnpj', models.CharField(blank=True, max_length=20)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('tipo_contrato', models.CharField(choices=[('spot', 'Eventual / Spot'), ('mensal', 'Contrato Mensal'), ('anual', 'Contrato Anual')], default='spot', max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('organization', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='ItemEstoque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150)),
                ('codigo', models.CharField(blank=True, help_text='SKU / código interno', max_length=50, unique=True)),
                ('categoria', models.CharField(choices=[('racao', 'Ração'), ('nucleo', 'Núcleo / Premix'), ('suplemento', 'Suplemento'), ('medicamento', 'Medicamento'), ('vacina', 'Vacina'), ('material', 'Material'), ('outro', 'Outro')], max_length=30)),
                ('unidade_medida', models.CharField(choices=[('kg', 'kg — Quilograma'), ('g', 'g — Grama'), ('l', 'L — Litro'), ('ml', 'ml — Mililitro'), ('unidade', 'un — Unidade'), ('dose', 'dose — Dose'), ('saco', 'sc — Saco'), ('caixa', 'cx — Caixa'), ('m', 'm — Metro'), ('m2', 'm² — Metro quadrado')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('fabricante', models.CharField(blank=True, max_length=100)),
                ('especie_animal', models.CharField(blank=True, choices=[('bovino', 'Bovino'), ('suino', 'Suíno'), ('ave', 'Ave'), ('ovino', 'Ovino'), ('caprino', 'Caprino'), ('equino', 'Equino'), ('multiplo', 'Múltiplas espécies'), ('outro', 'Outro')], max_length=30)),
                ('estoque_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('principio_ativo', models.CharField(blank=True, max_length=150)),
                ('concentracao', models.CharField(blank=True, max_length=100)),
                ('via_aplicacao', models.CharField(blank=True, choices=[('oral', 'Oral'), ('injetavel', 'Injetável'), ('topica', 'Tópica'), ('subcutanea', 'Subcutânea'), ('intramuscular', 'Intramuscular'), ('intravenosa', 'Intravenosa'), ('outra', 'Outra')], max_length=30)),
                ('carencia_dias', models.PositiveIntegerField(blank=True, help_text='Carência abate/leite (dias)', null=True)),
                ('registro_mapa', models.CharField(blank=True, max_length=50)),
                ('exige_receituario', models.BooleanField(default=False)),
                ('medicamento_controlado', models.BooleanField(default=False)),
                ('temperatura_minima', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperatura_maxima', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('doses_por_embalagem', models.PositiveIntegerField(blank=True, null=True)),
                ('volume_por_dose', models.CharField(blank=True, max_length=30)),
                ('composicao', models.TextField(blank=True, help_text='Composição / garantias')),
                ('indicacao_uso', models.TextField(blank=True)),
                ('modo_uso', models.TextField(blank=True, help_text='Dosagem / modo de preparo')),
                ('peso_embalagem', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Item de Estoque',
                'verbose_name_plural': 'Itens de Estoque',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoteEstoque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_lote', models.CharField(blank=True, max_length=100)),
                ('data_fabricacao', models.DateField(blank=True, null=True)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('quantidade_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_atual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('local_armazenamento', models.CharField(blank=True, choices=[('deposito', 'Depósito Geral'), ('camara_fria', 'Câmara Fria'), ('silo', 'Silo'), ('armario', 'Armário / Farmácia'), ('tanque', 'Tanque'), ('outro', 'Outro')], max_length=30)),
                ('nota_fiscal', models.CharField(blank=True, max_length=50)),
                ('data_entrada', models.DateField()),
                ('observacao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='inventory.fornecedor')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventory.itemestoque')),
            ],
            options={
                'verbose_name': 'Lote de Estoque',
                'verbose_name_plural': 'Lotes de Estoque',
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('item', 'numero_lote')},
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ajuste', 'Ajuste'), ('perda', 'Perda / Quebra'), ('vencimento', 'Descarte por Vencimento'), ('transferencia', 'Transferência')], max_length=30)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='farms.farm')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='inventory.itemestoque')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='inventory.loteestoque')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_estoque', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
