# Generated by Django 5.2.13 on 2026-04-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='fornecedor_logos/'),
        ),
    ]
