# Generated by Django 5.2.13 on 2026-04-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_fornecedor_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='telefone_2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='telefone_3',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
