# Generated by Django 5.2.13 on 2026-04-25 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_add_telefones_fornecedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='contato_principal',
        ),
    ]
