# Generated by Django 5.2.13 on 2026-04-26 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_contato_principal_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo',
            field=models.CharField(choices=[('compra', 'Compra'), ('venda', 'Venda'), ('consumo', 'Consumo'), ('perda', 'Perda')], max_length=30),
        ),
    ]
