# Generated by Django 5.2.13 on 2026-04-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_update_tipo_movimentacao_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemestoque',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10),
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='codigo',
            field=models.CharField(blank=True, help_text='SKU / código interno', max_length=50, null=True, unique=True),
        ),
    ]
