# Generated by Django 5.2.13 on 2026-04-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_add_prioridade_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='telefone_2',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='telefone_3',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cep',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='contatos_adicionais',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo',
            field=models.CharField(choices=[('compra', 'Compra'), ('venda', 'Venda'), ('consumo', 'Consumo'), ('perda', 'Perda'), ('entrada', 'Entrada'), ('saida', 'Saída'), ('vencimento', 'Vencimento'), ('ajuste', 'Ajuste')], max_length=30),
        ),
    ]
