# Generated by Django 5.2.13 on 2026-04-28 02:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_fornecedor_telefone_2_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fornecedor',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='fornecedores/'),
        ),
        migrations.CreateModel(
            name='FornecedorContato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('telefone', 'Telefone'), ('email', 'E-mail')], max_length=20)),
                ('label', models.CharField(blank=True, help_text='Ex: Vendas, Financeiro, WhatsApp', max_length=50)),
                ('valor', models.CharField(max_length=150)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='inventory.fornecedor')),
            ],
            options={
                'verbose_name': 'Contato do Fornecedor',
                'verbose_name_plural': 'Contatos do Fornecedor',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='contatos_adicionais',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='telefone',
        ),
    ]
