# Generated by Django 5.2.13 on 2026-04-28 03:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_fornecedor_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='estado',
        ),
        migrations.CreateModel(
            name='FornecedorEndereco',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, help_text='Ex: Matriz, Entrega', max_length=50)),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('logradouro', models.CharField(blank=True, max_length=255)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='inventory.fornecedor')),
            ],
            options={
                'verbose_name': 'Endereço de Fornecedor',
                'verbose_name_plural': 'Endereços de Fornecedores',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
