# Generated by Django 5.2.13 on 2026-04-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_fornecedor_cep_remove_fornecedor_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedorendereco',
            name='bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fornecedorendereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='fornecedorendereco',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='fornecedorendereco',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
    ]
