# Generated by Django 5.2.13 on 2026-04-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_fornecedorendereco_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedorendereco',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
