# Generated by Django 5.2.13 on 2026-04-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_fornecedorendereco_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL da logo externa (Clearbit, etc)', max_length=500, null=True),
        ),
    ]
