# Generated by Django 5.2.13 on 2026-04-28 04:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_fornecedor_logo_url'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaEstoque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('estoque_baixo', 'Estoque Baixo'), ('vencimento_proximo', 'Vencimento Próximo'), ('vencido', 'Vencido'), ('outro', 'Outro')], default='estoque_baixo', max_length=30)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('lido', models.BooleanField(default=False)),
                ('resolvido', models.BooleanField(default=False)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='inventory.itemestoque')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_alerts', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Alerta de Estoque',
                'verbose_name_plural': 'Alertas de Estoque',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
