# Generated by Django 5.2.13 on 2026-04-28 05:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alertaestoque'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaRacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('ativa', models.BooleanField(default=True)),
                ('item_final', models.ForeignKey(blank=True, help_text='O item de estoque (Ração) que será gerado por esta fórmula', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formulas_como_resultado', to='inventory.itemestoque')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas_racao', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Fórmula de Ração',
                'verbose_name_plural': 'Fórmulas de Ração',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProducaoRacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_producao', models.DateTimeField(auto_now_add=True)),
                ('quantidade_teorica', models.DecimalField(decimal_places=2, help_text='Quantidade planejada (kg)', max_digits=10)),
                ('quantidade_real', models.DecimalField(decimal_places=2, help_text='Quantidade que efetivamente rendeu (kg)', max_digits=10)),
                ('custo_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(default='concluida', max_length=20)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producoes', to='inventory.formularacao')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producoes_racao', to='organizations.organization')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producoes_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produção de Ração',
                'verbose_name_plural': 'Produções de Ração',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormulaIngrediente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('percentual', models.DecimalField(decimal_places=2, help_text='Percentual (0 a 100) na fórmula', max_digits=5)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usado_em_formulas', to='inventory.itemestoque')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='inventory.formularacao')),
            ],
            options={
                'verbose_name': 'Ingrediente da Fórmula',
                'verbose_name_plural': 'Ingredientes das Fórmulas',
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('formula', 'item')},
            },
        ),
    ]
