# Generated by Django 5.2.13 on 2026-05-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_formularacao_producaoracao_formulaingrediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularacao',
            name='especie_animal',
            field=models.CharField(blank=True, choices=[('bovino', 'Bovino'), ('suino', 'Suíno'), ('ave', 'Ave'), ('ovino', 'Ovino'), ('caprino', 'Caprino'), ('equino', 'Equino'), ('multiplo', 'Múltiplas espécies'), ('outro', 'Outro')], help_text='Espécie animal para a qual esta fórmula é destinada', max_length=30),
        ),
    ]
