# Generated by Django 5.2.13 on 2026-05-05 01:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
        ('inventory', '0015_add_especie_animal_to_formularacao'),
        ('livestock', '0002_animalbatch_category_animalbatch_gender_and_more'),
        ('organizations', '0002_organizationaddress_organizationcontact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoRacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('custo_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tipo_registro', models.CharField(choices=[('total_periodo', 'Total no Período'), ('diario', 'Consumo Diário'), ('por_cabeca', 'Por Cabeça')], default='total_periodo', max_length=30)),
                ('observacao', models.TextField(blank=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_racao', to='farms.farm')),
                ('item_estoque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_registrados', to='inventory.itemestoque')),
                ('lote_animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='livestock.animalbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_racao', to='organizations.organization')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos_lancados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consumo de Ração',
                'verbose_name_plural': 'Consumos de Ração',
                'ordering': ['-data_inicio'],
                'abstract': False,
            },
        ),
    ]
