# Generated by Django 5.2.13 on 2026-05-05 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_add_consumo_racao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemestoque',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='itemestoque',
            name='marca',
        ),
    ]
