# Generated by Django 5.2.13 on 2026-05-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_remove_itemestoque_codigo_remove_itemestoque_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemestoque',
            name='categoria',
            field=models.CharField(choices=[('racao', 'Ração'), ('nucleo', 'Núcleo / Premix'), ('suplemento', 'Suplemento'), ('medicamento', 'Medicamento'), ('vacina', 'Vacina'), ('material', 'Material'), ('semen', 'Sêmen'), ('outro', 'Outro')], max_length=30),
        ),
    ]
