# Generated by Django 5.2.13 on 2026-05-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_itemestoque_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemestoque',
            name='tipo_semen',
            field=models.CharField(blank=True, choices=[('convencional', 'Convencional'), ('sexado_macho', 'Sexado Macho'), ('sexado_femea', 'Sexado Fêmea')], help_text='Classificação do sêmen (Convencional, Sexado Macho/Fêmea)', max_length=20),
        ),
    ]
