# Generated by Codex on 2026-06-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0019_itemestoque_tipo_semen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemestoque",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("racao", "Ração"),
                    ("nucleo", "Núcleo / Premix"),
                    ("suplemento", "Suplemento"),
                    ("semente", "Semente"),
                    ("fertilizante", "Fertilizante / Adubo"),
                    ("defensivo", "Defensivo Agrícola"),
                    ("corretivo", "Corretivo de Solo"),
                    ("medicamento", "Medicamento"),
                    ("vacina", "Vacina"),
                    ("material", "Material"),
                    ("semen", "Sêmen"),
                    ("outro", "Outro"),
                ],
                max_length=30,
            ),
        ),
    ]
