"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {BadgeDollarSign,CheckCircle2,LoaderCircle} from "lucide-react";
import apiClient from "@/services/api";
import styles from "../operations.module.css";
type Batch={id:string;batch_code:string;name?:string;quantity:number;avg_weight_kg?:number;phase?:string;status:string;species_code?:string;notes?:string};
type Transaction={id:string;description:string;amount:string;due_date:string;reference?:string};
const money=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
export default function SalesPage(){const [batches,setBatches]=useState<Batch[]>([]),[history,setHistory]=useState<Transaction[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");const [form,setForm]=useState({batch:"",date:new Date().toISOString().slice(0,10),buyer:"",amount:"",notes:""});
 const load=()=>Promise.all([apiClient.get("/livestock/batches/",{params:{species:"suinos",status:"active",page_size:200}}),apiClient.get("/finance/transactions/",{params:{page_size:100}})]).then(([a,b])=>{const all:Batch[]=a.data.results||a.data||[];setBatches(all.filter(x=>x.species_code==="suinos"&&x.status==="active"));setHistory((b.data.results||b.data||[]).filter((x:Transaction)=>x.reference?.startsWith("SALE-BATCH-")))}).finally(()=>setLoading(false));useEffect(()=>{load().catch(()=>setError("Não foi possível carregar os dados."))},[]);
 const chosen=batches.find(x=>x.id===form.batch),amount=Number(form.amount.replace(",","."))||0,totalWeight=(Number(chosen?.avg_weight_kg)||0)*(chosen?.quantity||0);
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!chosen||amount<=0)return;setSaving(true);setError("");setMessage("");try{await apiClient.patch(`/livestock/batches/${chosen.id}/`,{status:"sold",exit_date:form.date,sale_value:amount,notes:[chosen.name,form.buyer&&`Comprador: ${form.buyer}`,form.notes].filter(Boolean).join(" | ")});setMessage("Venda registrada e receita lançada no financeiro.");setForm({batch:"",date:new Date().toISOString().slice(0,10),buyer:"",amount:"",notes:""});await load()}catch{setError("Não foi possível registrar a venda. Confira os dados e tente novamente.")}finally{setSaving(false)}};
 return <div className={`${styles.page} ${styles.sale}`}><header className={styles.header}><div><span className={styles.headerIcon}><BadgeDollarSign size={27}/></span><div><h1>Venda de Animais</h1><p>Registre a saída do lote e gere a receita automaticamente.</p></div></div><Link className={styles.back} href="/home/rebanho/suinos">← Voltar para Suínos</Link></header><div className={styles.layout}><form className={styles.card} onSubmit={submit}><h2>Nova venda</h2><p>Este lançamento encerra o lote selecionado e integra o valor ao financeiro.</p>{message&&<div className={styles.success}><CheckCircle2 size={17}/>{message}</div>}{error&&<div className={styles.error}>{error}</div>}<div className={styles.grid}><div className={`${styles.field} ${styles.wide}`}><label>Lote vendido</label><select required value={form.batch} onChange={e=>setForm({...form,batch:e.target.value})}><option value="">Selecione um lote ativo</option>{batches.map(x=><option key={x.id} value={x.id}>{x.batch_code} — {x.quantity} animais</option>)}</select></div><div className={styles.field}><label>Data da venda</label><input required type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></div><div className={styles.field}><label>Comprador</label><input required value={form.buyer} onChange={e=>setForm({...form,buyer:e.target.value})} placeholder="Nome ou empresa"/></div><div className={`${styles.field} ${styles.wide}`}><label>Valor total da venda (R$)</label><input required inputMode="decimal" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} placeholder="0,00"/></div>{chosen&&<div className={styles.summary}><div><span>Animais no lote</span><strong>{chosen.quantity}</strong></div><div><span>Peso total estimado</span><strong>{totalWeight?`${totalWeight.toLocaleString("pt-BR")} kg`:"Não informado"}</strong></div></div>}<div className={`${styles.field} ${styles.wide}`}><label>Observações</label><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div><button className={styles.submit} disabled={saving||!chosen||amount<=0}>{saving?<LoaderCircle size={18}/>:<BadgeDollarSign size={18}/>}Registrar venda</button></div></form><section className={styles.card}><h2>Vendas recentes</h2><p>Receitas criadas pela venda de lotes.</p><div className={styles.history}>{loading?<div className={styles.empty}>Carregando…</div>:history.length?history.slice(0,8).map(x=><div className={styles.row} key={x.id}><div><strong>{x.description}</strong><small>{new Date(`${x.due_date}T00:00:00`).toLocaleDateString("pt-BR")}</small></div><span className={styles.amount}>{money.format(Number(x.amount))}</span></div>):<div className={styles.empty}>Nenhuma venda registrada.</div>}</div></section></div></div>}
