# Generated by Django 5.2.13 on 2026-04-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalbatch',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='animalbatch',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='animalbatch',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='animalbatch',
            name='origin',
            field=models.CharField(choices=[('purchased', 'Comprado'), ('born', 'Nascido'), ('donated', 'Doado')], default='purchased', max_length=20),
        ),
        migrations.AddField(
            model_name='animalbatch',
            name='purchase_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
