# Generated by Django 5.2.13 on 2026-05-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_animalbatch_category_animalbatch_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalbatch',
            name='sale_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
