# Generated by Django 5.2.13 on 2026-05-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0003_animalbatch_sale_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalbatch',
            name='category',
            field=models.CharField(blank=True, choices=[('Bezerro', 'Bezerro'), ('Garrote', 'Garrote'), ('Novilha', 'Novilha'), ('Touro', 'Touro'), ('Matriz', 'Matriz'), ('Leitão', 'Leitão'), ('Terminação', 'Terminação'), ('Cachaço', 'Cachaço'), ('Pinto', 'Pinto'), ('Frango de Corte', 'Frango de Corte'), ('Poedeira', 'Poedeira')], max_length=50, null=True),
        ),
    ]
