# Generated by Django 5.2.13 on 2026-05-13 02:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
        ('livestock', '0004_alter_animalbatch_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(help_text='Brinco, tatuagem ou nome', max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], default='F', max_length=1)),
                ('category', models.CharField(blank=True, choices=[('Bezerro', 'Bezerro'), ('Garrote', 'Garrote'), ('Novilha', 'Novilha'), ('Touro', 'Touro'), ('Matriz', 'Matriz'), ('Leitão', 'Leitão'), ('Terminação', 'Terminação'), ('Cachaço', 'Cachaço'), ('Pinto', 'Pinto'), ('Frango de Corte', 'Frango de Corte'), ('Poedeira', 'Poedeira')], max_length=50, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('finished', 'Finished'), ('dead', 'Dead')], default='active', max_length=20)),
                ('reproductive_status', models.CharField(choices=[('vazia', 'Vazia'), ('em_preparo', 'Em Preparo'), ('pronta', 'Pronta para Serviço'), ('coberta', 'Coberta (Aguardando DG)'), ('gestante', 'Gestante'), ('lactante', 'Lactante'), ('descanso', 'Em Descanso'), ('ativa', 'Ativa (Macho)')], default='em_preparo', max_length=20)),
                ('initial_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('current_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(blank=True, help_text='Lote de origem, se houver', null=True, on_delete=django.db.models.deletion.SET_NULL, to='livestock.animalbatch')),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='livestock.breed')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='farms.farm')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='livestock.species')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animals',
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('farm', 'identifier')},
            },
        ),
        migrations.CreateModel(
            name='Birth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birth_date', models.DateField()),
                ('live_born', models.PositiveIntegerField(default=0)),
                ('stillborn', models.PositiveIntegerField(default=0)),
                ('mummified', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('female', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='births', to='livestock.animal')),
            ],
            options={
                'verbose_name': 'Birth',
                'verbose_name_plural': 'Births',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Litter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weaning_date', models.DateField(blank=True, null=True)),
                ('weaned_quantity', models.PositiveIntegerField(default=0, help_text='Quantidade desmamada viva')),
                ('avg_weaning_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('birth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='litter', to='livestock.birth')),
            ],
            options={
                'verbose_name': 'Litter',
                'verbose_name_plural': 'Litters',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sire_info', models.CharField(blank=True, help_text='Informação do sêmen se não for animal cadastrado', max_length=100)),
                ('mating_date', models.DateField()),
                ('mating_type', models.CharField(choices=[('natural', 'Monta Natural'), ('ai', 'Inseminação Artificial'), ('iatf', 'IATF')], default='ai', max_length=20)),
                ('status', models.CharField(choices=[('pending_dg', 'Aguardando Diagnóstico'), ('confirmed', 'Prenhez Confirmada'), ('failed', 'Falha/Vazia')], default='pending_dg', max_length=20)),
                ('expected_birth_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('female', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matings_as_female', to='livestock.animal')),
                ('sire', models.ForeignKey(blank=True, help_text='Touro ou cachaço', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matings_as_sire', to='livestock.animal')),
            ],
            options={
                'verbose_name': 'Mating',
                'verbose_name_plural': 'Matings',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('expected_birth_date', models.DateField()),
                ('status', models.CharField(choices=[('ongoing', 'Em andamento'), ('completed', 'Concluída (Parto)'), ('lost', 'Perda/Aborto')], default='ongoing', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('female', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancies', to='livestock.animal')),
                ('mating', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancy', to='livestock.mating')),
            ],
            options={
                'verbose_name': 'Pregnancy',
                'verbose_name_plural': 'Pregnancies',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='birth',
            name='pregnancy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='birth', to='livestock.pregnancy'),
        ),
    ]
