# Generated by Django 5.2.13 on 2026-05-13 05:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
        ('livestock', '0005_animal_birth_litter_mating_pregnancy_birth_pregnancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incubation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('expected_hatch_date', models.DateField()),
                ('eggs_incubated', models.PositiveIntegerField(default=0)),
                ('eggs_hatched', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('incubating', 'Incubando'), ('hatched', 'Eclodido'), ('failed', 'Falha')], default='incubating', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(help_text='Lote de matrizes de origem', on_delete=django.db.models.deletion.CASCADE, related_name='incubations', to='livestock.animalbatch')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incubations', to='farms.farm')),
            ],
            options={
                'verbose_name': 'Incubation',
                'verbose_name_plural': 'Incubations',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
