# Generated by Django 5.2.13 on 2026-05-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0006_incubation'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalbatch',
            name='phase',
            field=models.CharField(blank=True, choices=[('creche', 'Creche'), ('crescimento', 'Crescimento'), ('engorda', 'Engorda'), ('gestacao_maternidade', 'Gestação/Maternidade'), ('reproducao', 'Reprodução'), ('outro', 'Outro')], help_text='Fase produtiva do lote (creche, crescimento, engorda, etc.)', max_length=30, null=True),
        ),
    ]
