# Generated by Django 5.2.13 on 2026-05-15 00:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
        ('livestock', '0007_animalbatch_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vaccine_name', models.CharField(max_length=100)),
                ('application_date', models.DateField()),
                ('next_dose_date', models.DateField(blank=True, null=True)),
                ('dose_type', models.CharField(choices=[('unica', 'Dose Única'), ('primeira', '1ª Dose'), ('segunda', '2ª Dose'), ('terceira', '3ª Dose'), ('reforco', 'Reforço')], default='unica', max_length=20)),
                ('dosage_ml', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('batch_number', models.CharField(blank=True, help_text='Número do lote da vacina', max_length=50)),
                ('applicator', models.CharField(blank=True, help_text='Responsável pela aplicação', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccinations', to='livestock.animal')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccinations', to='livestock.animalbatch')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='farms.farm')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vaccinations', to='livestock.species')),
            ],
            options={
                'verbose_name': 'Vaccination Record',
                'verbose_name_plural': 'Vaccination Records',
                'ordering': ['-application_date'],
                'abstract': False,
            },
        ),
    ]
