# Generated by Django 5.2.13 on 2026-05-15 01:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
        ('livestock', '0009_alter_animal_category_alter_animalbatch_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('weighing_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weights', to='livestock.animal')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weights', to='livestock.animalbatch')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='farms.farm')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weights', to='livestock.species')),
            ],
            options={
                'verbose_name': 'Weight Record',
                'verbose_name_plural': 'Weight Records',
                'ordering': ['-weighing_date'],
                'abstract': False,
            },
        ),
    ]
