# Generated by Django 5.2.13 on 2026-05-15 01:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
        ('livestock', '0010_weightrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feed_type', models.CharField(max_length=100)),
                ('quantity_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeding_records', to='livestock.animal')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeding_records', to='livestock.animalbatch')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_records', to='farms.farm')),
            ],
            options={
                'verbose_name': 'Feeding Record',
                'verbose_name_plural': 'Feeding Records',
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('treatment_type', models.CharField(choices=[('medication', 'Medicação'), ('exam', 'Exame'), ('surgery', 'Cirurgia'), ('other', 'Outro')], default='medication', max_length=20)),
                ('description', models.TextField()),
                ('application_date', models.DateField()),
                ('veterinary', models.CharField(blank=True, max_length=100)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='livestock.animal')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='farms.farm')),
            ],
            options={
                'verbose_name': 'Health Record',
                'verbose_name_plural': 'Health Records',
                'ordering': ['-application_date'],
                'abstract': False,
            },
        ),
    ]
