# Generated by Django 5.2.13 on 2026-05-15 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0011_feedingrecord_healthrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='dam_name',
            field=models.CharField(blank=True, help_text='Nome/registro da mãe se não cadastrada no sistema', max_length=100),
        ),
        migrations.AddField(
            model_name='animal',
            name='dam_ref',
            field=models.ForeignKey(blank=True, help_text='Mãe, se cadastrada no sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_as_dam', to='livestock.animal', verbose_name='Mãe'),
        ),
        migrations.AddField(
            model_name='animal',
            name='sire_name',
            field=models.CharField(blank=True, help_text='Nome/registro do pai se não cadastrado no sistema', max_length=100),
        ),
        migrations.AddField(
            model_name='animal',
            name='sire_ref',
            field=models.ForeignKey(blank=True, help_text='Reprodutor pai, se cadastrado no sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_as_sire', to='livestock.animal', verbose_name='Pai (Reprodutor)'),
        ),
    ]
