# Generated by Django 5.2.13 on 2026-05-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0012_animal_dam_name_animal_dam_ref_animal_sire_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='birth_count',
            field=models.PositiveIntegerField(default=0, help_text='Nº total de partos da fêmea'),
        ),
        migrations.AddField(
            model_name='animal',
            name='previous_phase',
            field=models.CharField(blank=True, help_text='Status reprodutivo anterior (para retorno após DG negativo)', max_length=30),
        ),
        migrations.AddField(
            model_name='birth',
            name='birth_order',
            field=models.PositiveIntegerField(default=1, help_text='Número/ordem do parto (1ª cria, 2ª cria...)'),
        ),
        migrations.AddField(
            model_name='birth',
            name='birth_time_end',
            field=models.TimeField(blank=True, help_text='Horário de término do parto', null=True),
        ),
        migrations.AddField(
            model_name='birth',
            name='birth_time_start',
            field=models.TimeField(blank=True, help_text='Horário de início do parto', null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='category',
            field=models.CharField(blank=True, choices=[('Bezerro', 'Bezerro'), ('Garrote', 'Garrote'), ('Novilha', 'Novilha'), ('Touro', 'Touro'), ('Matriz', 'Matriz'), ('Marrã', 'Marrã'), ('Vaca', 'Vaca'), ('Leitão', 'Leitão'), ('Terminação', 'Terminação'), ('Cachaço', 'Cachaço'), ('Aguardando Cobertura', 'Aguardando Cobertura'), ('Pinto', 'Pinto'), ('Frango de Corte', 'Frango de Corte'), ('Poedeira', 'Poedeira')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='reproductive_status',
            field=models.CharField(choices=[('vazia', 'Vazia'), ('em_preparo', 'Em Preparo'), ('pronta', 'Pronta para Serviço'), ('coberta', 'Coberta (Aguardando DG)'), ('gestante', 'Gestante'), ('lactante', 'Lactante'), ('descanso', 'Em Descanso'), ('ativa', 'Ativa (Macho)'), ('aguardando_cobertura', 'Aguardando Cobertura')], default='em_preparo', max_length=20),
        ),
        migrations.AlterField(
            model_name='animalbatch',
            name='category',
            field=models.CharField(blank=True, choices=[('Bezerro', 'Bezerro'), ('Garrote', 'Garrote'), ('Novilha', 'Novilha'), ('Touro', 'Touro'), ('Matriz', 'Matriz'), ('Marrã', 'Marrã'), ('Vaca', 'Vaca'), ('Leitão', 'Leitão'), ('Terminação', 'Terminação'), ('Cachaço', 'Cachaço'), ('Aguardando Cobertura', 'Aguardando Cobertura'), ('Pinto', 'Pinto'), ('Frango de Corte', 'Frango de Corte'), ('Poedeira', 'Poedeira')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animalbatch',
            name='phase',
            field=models.CharField(blank=True, choices=[('creche', 'Creche'), ('crescimento', 'Crescimento'), ('engorda', 'Engorda'), ('gestacao_maternidade', 'Gestação/Maternidade'), ('reproducao', 'Reprodução'), ('aguardando_cobertura', 'Aguardando Cobertura'), ('outro', 'Outro')], help_text='Fase produtiva do lote (creche, crescimento, engorda, etc.)', max_length=30, null=True),
        ),
    ]
