# Generated by Django 5.2.13 on 2026-05-15 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0013_animal_birth_count_animal_previous_phase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalbatch',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_batches', to='livestock.animal'),
        ),
        migrations.AddField(
            model_name='birth',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birth_records', to='livestock.animalbatch'),
        ),
    ]
