# Generated by Django 5.2.13 on 2026-05-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0014_animalbatch_mother_birth_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='category',
            field=models.CharField(blank=True, choices=[('Bezerro', 'Bezerro'), ('Garrote', 'Garrote'), ('Novilha', 'Novilha'), ('Touro', 'Touro'), ('Matriz', 'Matriz'), ('Marrã', 'Marrã'), ('Vaca', 'Vaca'), ('Leitão', 'Leitão'), ('Terminação', 'Terminação'), ('Cachaço', 'Cachaço'), ('Reprodutor', 'Reprodutor'), ('Aguardando Cobertura', 'Aguardando Cobertura'), ('Pinto', 'Pinto'), ('Frango de Corte', 'Frango de Corte'), ('Poedeira', 'Poedeira')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animalbatch',
            name='category',
            field=models.CharField(blank=True, choices=[('Bezerro', 'Bezerro'), ('Garrote', 'Garrote'), ('Novilha', 'Novilha'), ('Touro', 'Touro'), ('Matriz', 'Matriz'), ('Marrã', 'Marrã'), ('Vaca', 'Vaca'), ('Leitão', 'Leitão'), ('Terminação', 'Terminação'), ('Cachaço', 'Cachaço'), ('Reprodutor', 'Reprodutor'), ('Aguardando Cobertura', 'Aguardando Cobertura'), ('Pinto', 'Pinto'), ('Frango de Corte', 'Frango de Corte'), ('Poedeira', 'Poedeira')], max_length=50, null=True),
        ),
    ]
