# Generated by Django 5.2.13 on 2026-05-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0015_alter_animal_category_alter_animalbatch_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='birth',
            name='avg_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso médio dos leitões ao nascimento', max_digits=8, null=True),
        ),
    ]
