# Generated by Django 5.2.13 on 2026-05-22 06:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0016_birth_avg_weight_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalbatch',
            name='source_batches',
            field=models.ManyToManyField(blank=True, related_name='merged_into', to='livestock.animalbatch'),
        ),
        migrations.CreateModel(
            name='BatchPhaseHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('avg_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('entry_date', models.DateField()),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_histories', to='livestock.animalbatch')),
            ],
            options={
                'verbose_name': 'Batch Phase History',
                'verbose_name_plural': 'Batch Phase Histories',
                'ordering': ['entry_date'],
                'abstract': False,
            },
        ),
    ]
