# Generated by Django 5.2.13 on 2026-05-23 02:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
        ('livestock', '0018_disease_sanitaryalert_symptom_disease_symptoms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoEvento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_evento', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('data_evento', models.DateField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos_operacionais', to='farms.farm')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='livestock.animalbatch')),
                ('matriz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='livestock.animal')),
            ],
            options={
                'verbose_name': 'Histórico de Evento',
                'verbose_name_plural': 'Históricos de Eventos',
                'ordering': ['-data_evento'],
                'abstract': False,
            },
        ),
    ]
