# Generated by Django 5.0 on 2026-05-23
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0019_itemestoque_tipo_semen"),
        ("livestock", "0019_historicoevento"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaccinationrecord",
            name="vaccine_item",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.itemestoque",
                related_name="vacinacoes",
                help_text="Item do estoque (vacina) vinculado",
            ),
        ),
    ]
