# Generated by Django 5.2.14 on 2026-05-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0020_vaccinationrecord_vaccine_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='birth',
            name='mortality',
            field=models.PositiveIntegerField(default=0, help_text='Mortalidade pós-parto (registrada durante maternidade)'),
        ),
    ]
