# Generated by Django 5.2.15 on 2026-06-04 17:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0021_birth_mortality'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heat_number', models.PositiveSmallIntegerField(default=1, help_text='Número do cio (1º, 2º, 3º...)')),
                ('heat_date', models.DateField(help_text='Data do cio (real ou prevista)')),
                ('is_predicted', models.BooleanField(default=False, help_text='True se a data for uma previsão automática')),
                ('notes', models.TextField(blank=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heat_records', to='livestock.animal')),
            ],
            options={
                'verbose_name': 'Registro de Cio',
                'verbose_name_plural': 'Registros de Cio',
                'ordering': ['animal', 'heat_number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LitterMedication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicamento', models.CharField(max_length=150)),
                ('dosagem', models.CharField(blank=True, max_length=100)),
                ('data_aplicacao', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('responsavel', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(blank=True, help_text='Lote da Creche/Crescimento/Engorda herdeiro do histórico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litter_medications', to='livestock.animalbatch')),
                ('birth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='livestock.birth')),
            ],
            options={
                'verbose_name': 'Medicamento da Leitegada',
                'verbose_name_plural': 'Medicamentos da Leitegada',
                'ordering': ['-data_aplicacao'],
                'abstract': False,
            },
        ),
    ]
