# Generated by Django 5.2.13 on 2026-09-19 23:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0028_littermedication_inventory_fields'),
        ('organizations', '0002_organizationaddress_organizationcontact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcknowledgedOperationalAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_key', models.CharField(max_length=64)),
                ('alert_text', models.CharField(blank=True, max_length=500)),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledged_operational_alerts', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledged_operational_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta operacional confirmado',
                'verbose_name_plural': 'Alertas operacionais confirmados',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'organization', 'alert_key'], name='livestock_a_user_id_ddbd06_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'organization', 'alert_key'), name='uniq_user_operational_alert_ack')],
            },
        ),
    ]
