# Generated by Django 5.2.13 on 2026-09-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0029_acknowledgedoperationalalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationrecord',
            name='inventory_cost_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custo real descontado do estoque no momento da vacinação (snapshot)', max_digits=10, null=True),
        ),
    ]
