# Generated by Django 5.2.17 on 2026-10-02 00:18

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies: ClassVar[list] = [
        ('livestock', '0030_add_vaccination_cost_snapshot'),
    ]

    operations: ClassVar[list] = [
        migrations.AddField(
            model_name='animalbatch',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
