# Generated by Django 5.2.13 on 2026-10-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_reliability_and_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='whatsapp_reproductive_alerts',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='channel',
            field=models.CharField(choices=[('email', 'E-mail'), ('web_push', 'Web Push'), ('whatsapp_web', 'WhatsApp Web')], max_length=20),
        ),
    ]
