# Generated by Django 5.2.13 on 2026-07-15 03:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organizationaddress_organizationcontact'),
        ('platform_admin', '0003_backgroundtaskrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-starts_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('info', 'Informativo'), ('success', 'Sucesso'), ('warning', 'Atenção'), ('critical', 'Crítico')], default='info', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-starts_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('rollout_percentage', models.PositiveSmallIntegerField(default=100)),
                ('allowed_plans', models.JSONField(blank=True, default=list)),
                ('allowed_organizations', models.ManyToManyField(blank=True, related_name='feature_flag_overrides', to='organizations.organization')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
    ]
