# Generated by Django 5.2.13 on 2026-07-16 01:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0004_maintenancewindow_systemannouncement_featureflag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SqlQueryExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query_text', models.TextField()),
                ('status', models.CharField(choices=[('success', 'Concluída'), ('rejected', 'Rejeitada'), ('error', 'Erro')], max_length=20)),
                ('duration_ms', models.PositiveBigIntegerField(default=0)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('was_truncated', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sql_query_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
