# Generated by Django 5.2.13 on 2026-07-16 02:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0006_developersandboxgrant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SandboxExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_sha256', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('running', 'Em execução'), ('success', 'Concluída'), ('error', 'Erro'), ('timeout', 'Tempo excedido'), ('service_error', 'Falha do serviço')], default='running', max_length=20)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('stdout_bytes', models.PositiveIntegerField(default=0)),
                ('stderr_bytes', models.PositiveIntegerField(default=0)),
                ('error_message', models.CharField(blank=True, max_length=300)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='platform_admin.developersandboxgrant')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sandbox_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
