# Generated by Django 5.2.13 on 2026-08-07 04:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def migrate_legacy_pipeline_statuses(apps, schema_editor):
    DemoRequest = apps.get_model("platform_admin", "DemoRequest")
    DemoRequest.objects.filter(status="pending").update(status="new")
    DemoRequest.objects.filter(status="approved").update(status="contacted")
    DemoRequest.objects.filter(status="rejected").update(status="lost", loss_reason="Rejeitada no fluxo anterior")


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0010_demorequest_attribution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_name', models.CharField(db_index=True, max_length=80)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('path', models.CharField(blank=True, db_index=True, max_length=255)),
                ('variant', models.CharField(blank=True, max_length=40)),
                ('utm_source', models.CharField(blank=True, max_length=120)),
                ('utm_medium', models.CharField(blank=True, max_length=120)),
                ('utm_campaign', models.CharField(blank=True, max_length=120)),
                ('value', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='demorequest',
            name='ab_variant',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_demo_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='estimated_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='loss_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='next_action_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='demorequest',
            name='status',
            field=models.CharField(choices=[('new', 'Novo'), ('contacted', 'Contato realizado'), ('scheduled', 'Demonstração agendada'), ('proposal', 'Proposta enviada'), ('negotiation', 'Em negociação'), ('won', 'Convertido'), ('lost', 'Perdido'), ('pending', 'Pendente (legado)'), ('approved', 'Aprovada (legado)'), ('rejected', 'Rejeitada (legado)')], db_index=True, default='new', max_length=20),
        ),
        migrations.RunPython(migrate_legacy_pipeline_statuses, migrations.RunPython.noop),
        migrations.CreateModel(
            name='DemoAppointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=45)),
                ('timezone', models.CharField(default='America/Recife', max_length=60)),
                ('meeting_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Agendada'), ('completed', 'Realizada'), ('cancelled', 'Cancelada'), ('no_show', 'Não compareceu')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_demo_appointments', to=settings.AUTH_USER_MODEL)),
                ('demo_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='platform_admin.demorequest')),
            ],
            options={
                'ordering': ('starts_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DemoRequestActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(db_index=True, max_length=60)),
                ('description', models.CharField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('demo_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='platform_admin.demorequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
