# Generated by Django 5.2.13 on 2026-08-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0011_marketingevent_demorequest_ab_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demorequest',
            name='preferred_demo_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
