# Generated by Django 5.2.15 on 2026-08-23 15:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_seed_ai_entitlements'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.SlugField(unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('base_url', models.URLField(max_length=500)),
                ('api_key_env_var', models.CharField(blank=True, help_text='Nome da variável de ambiente que contém a credencial; nunca armazene a chave aqui.', max_length=100)),
                ('is_enabled', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=45)),
                ('last_health_check_at', models.DateTimeField(blank=True, null=True)),
                ('last_health_status', models.CharField(choices=[('unknown', 'Não verificado'), ('healthy', 'Disponível'), ('degraded', 'Instável'), ('unavailable', 'Indisponível')], default='unknown', max_length=20)),
                ('last_health_message', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('display_name',),
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='unique_default_ai_provider'), models.CheckConstraint(condition=models.Q(('timeout_seconds__gte', 1)), name='ai_provider_timeout_positive')],
            },
        ),
        migrations.CreateModel(
            name='AIModelSyncRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('running', 'Executando'), ('success', 'Concluída'), ('failure', 'Falhou')], default='running', max_length=20)),
                ('trigger', models.CharField(choices=[('scheduled', 'Agendada'), ('manual', 'Manual')], default='scheduled', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('models_found', models.PositiveIntegerField(default=0)),
                ('free_models_found', models.PositiveIntegerField(default=0)),
                ('models_created', models.PositiveIntegerField(default=0)),
                ('models_updated', models.PositiveIntegerField(default=0)),
                ('models_unavailable', models.PositiveIntegerField(default=0)),
                ('added_model_ids', models.JSONField(blank=True, default=list)),
                ('unavailable_model_ids', models.JSONField(blank=True, default=list)),
                ('error_class', models.CharField(blank=True, max_length=150)),
                ('error_message', models.TextField(blank=True)),
                ('response_summary', models.JSONField(blank=True, default=dict)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_sync_runs', to='ai_assistant.aiproviderconfiguration')),
            ],
            options={
                'ordering': ('-started_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['provider', 'status', 'started_at'], name='ai_assistan_provide_b798e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=150)),
                ('display_name', models.CharField(max_length=150)),
                ('endpoint_type', models.CharField(choices=[('chat_completions', 'Chat Completions'), ('responses', 'Responses')], default='chat_completions', max_length=30)),
                ('is_free', models.BooleanField(db_index=True, default=False)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('supports_streaming', models.BooleanField(default=False)),
                ('supports_tools', models.BooleanField(default=False)),
                ('input_price', models.DecimalField(blank=True, decimal_places=8, max_digits=14, null=True)),
                ('output_price', models.DecimalField(blank=True, decimal_places=8, max_digits=14, null=True)),
                ('context_window', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='ai_assistant.aiproviderconfiguration')),
            ],
            options={
                'ordering': ('priority', 'display_name'),
                'abstract': False,
                'indexes': [models.Index(fields=['provider', 'is_free', 'is_available', 'is_enabled'], name='ai_assistan_provide_b82100_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_id'), name='unique_ai_model_per_provider'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('provider',), name='unique_primary_ai_model_per_provider'), models.CheckConstraint(condition=models.Q(('input_price__isnull', True), ('input_price__gte', 0), _connector='OR'), name='ai_model_input_price_nonnegative'), models.CheckConstraint(condition=models.Q(('output_price__isnull', True), ('output_price__gte', 0), _connector='OR'), name='ai_model_output_price_nonnegative')],
            },
        ),
    ]
