# Generated by Django 5.2.15 on 2026-08-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_aiproviderconfiguration_aimodelsyncrun_aimodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessage',
            name='fallback_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='provider',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='provider_attempts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='aimessage',
            name='model',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
