# Generated by Django 5.2.17 on 2026-10-03 15:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0005_aiproviderconfiguration_encrypted_api_key'),
        ('organizations', '0002_organizationaddress_organizationcontact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('faq', 'Dúvida frequente'), ('tutorial', 'Tutorial')], default='faq', max_length=20)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('content', models.TextField()),
                ('video_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('position', 'title', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupportConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(default='global', editable=False, max_length=20, unique=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15)),
                ('ai_enabled', models.BooleanField(default=True)),
                ('daily_question_limit', models.PositiveSmallIntegerField(default=20)),
                ('welcome_message', models.CharField(default='Olá! Posso ajudar com cadastros, lançamentos e o uso do Fazenda Mais. Conte o que você está tentando fazer.', max_length=500)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='aiconversation',
            name='subject',
            field=models.CharField(choices=[('general', 'Geral'), ('crops', 'Plantações'), ('livestock', 'Animais'), ('feeding', 'Alimentação'), ('management', 'Gestão rural'), ('support', 'Suporte do sistema')], default='general', max_length=20),
        ),
        migrations.CreateModel(
            name='SupportUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.DateField()),
                ('questions_used', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('organization', 'user', 'day'), name='unique_support_daily_usage')],
            },
        ),
    ]
