# Generated by Django 5.2.17 on 2026-10-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0007_seed_support_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessage',
            name='cached_tokens',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='cost_source',
            field=models.CharField(choices=[('unknown', 'Não informado'), ('reported', 'Informado pelo provedor'), ('estimated', 'Estimado pelo catálogo')], default='unknown', max_length=12),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='cost_usd',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='reasoning_tokens',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='requested_model',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='aiproviderconfiguration',
            name='allow_paid_models',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiproviderconfiguration',
            name='max_model_attempts',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='aiproviderconfiguration',
            name='max_output_tokens',
            field=models.PositiveSmallIntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='aiproviderconfiguration',
            name='prefer_free_models',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='aiusage',
            name='estimated_cost_usd',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=18),
        ),
    ]
