"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { Boxes, CalendarDays, Check, ChevronRight, CircleDollarSign, Factory, PackageOpen, Play, Scale, Settings2 } from "lucide-react";
import { apiClient } from "@/services/api";
import styles from "./feed-production.module.css";

type Ingredient={id:number;item:number;item_nome:string;percentual:string;estoque_atual:string;custo_medio:string};
type Formula={id:number;nome:string;descricao:string;item_final:number|null;item_final_nome:string|null;ativa:boolean;ingredientes:Ingredient[]};
type Production={id:number;data_producao:string;formula_nome:string;quantidade_teorica:string;quantidade_real:string;custo_total:string;responsavel_nome:string;status:string};
const speciesLabel:Record<string,string>={suino:"Suínos",ave:"Aves",bovino:"Bovinos"};
const money=(value:number)=>value.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const number=(value:number,digits=2)=>value.toLocaleString("pt-BR",{minimumFractionDigits:digits,maximumFractionDigits:digits});

export function FeedProductionDashboard({species,showHeader=true}:{species?:string;showHeader?:boolean}={}){
 const[formulas,setFormulas]=useState<Formula[]>([]),[productions,setProductions]=useState<Production[]>([]),[formulaId,setFormulaId]=useState(""),[quantity,setQuantity]=useState(1000),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[producing,setProducing]=useState(false),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
 const formulaPath=species?`/home/rebanho/${species==="suino"?"suinos":species==="ave"?"aves":"bovinos"}/racao/gerenciar-formulas`:"/home/estoque/producao-racao/gerenciar-formulas";
 const load=async()=>{const suffix=species?`?especie=${species}`:"";const[formulaResponse,productionResponse]=await Promise.all([apiClient.get(`/inventory/formulas/${suffix}`),apiClient.get(`/inventory/producoes/${suffix}`)]);const formulaList=formulaResponse.data.results||formulaResponse.data||[];setFormulas(formulaList);setProductions(productionResponse.data.results||productionResponse.data||[]);setFormulaId(current=>formulaList.some((item:Formula)=>String(item.id)===current)?current:String(formulaList[0]?.id||""));};
 useEffect(()=>{setLoading(true);load().catch(()=>setMessage("Não foi possível carregar os dados da fábrica de ração.")).finally(()=>setLoading(false));},[species]);
 const formula=useMemo(()=>formulas.find(item=>String(item.id)===formulaId),[formulas,formulaId]);
 const summary=useMemo(()=>{const items=(formula?.ingredientes||[]).map(item=>{const percentage=Number(item.percentual),required=quantity*percentage/100,available=Number(item.estoque_atual),unitCost=Number(item.custo_medio),totalCost=required*unitCost;return{...item,percentage,required,available,unitCost,totalCost,enough:available>=required};});const totalCost=items.reduce((sum,item)=>sum+item.totalCost,0),totalAvailable=items.reduce((sum,item)=>sum+item.available,0);return{items,totalCost,totalAvailable,costKg:quantity>0?totalCost/quantity:0,enough:items.length>0&&items.every(item=>item.enough)};},[formula,quantity]);
 const produce=async()=>{if(!formula||quantity<=0){setMessage("Selecione uma fórmula e informe uma quantidade válida.");return;}if(!summary.enough){setMessage("Existem ingredientes com estoque insuficiente para esta produção.");return;}if(!window.confirm(`Confirmar a produção de ${number(quantity)} kg da ração ${formula.nome}?`))return;try{setProducing(true);setMessage("");const response=await apiClient.post("/inventory/producoes/produzir/",{formula_id:formula.id,quantidade_teorica:quantity,quantidade_real:quantity,data_producao:date});setMessage(response.data.status||"Produção registrada com sucesso.");await load();}catch(error:any){setMessage(error?.response?.data?.error||"Não foi possível registrar a produção.");}finally{setProducing(false);}};
 return <div className={styles.page}>
  {showHeader&&<header className={styles.header}><div><nav><Link href="/home/rebanho/suinos">Suínos</Link><ChevronRight/> <strong>Fábrica de Ração</strong></nav><h1>Fábrica de Ração</h1><p>Produza rações de forma rápida, precisa e com eficiência.</p></div><Link href={formulaPath} className={styles.manage}><Settings2/>Gerenciar Fórmulas de Ração</Link></header>}
  {message&&<div className={message.toLowerCase().includes("sucesso")||message.toLowerCase().includes("registrada")?styles.success:styles.alert}>{message}</div>}
  <div className={styles.layout}><main>
   <section className={styles.card}><SectionTitle number="1" title="Ordem de Lançar Produção" text="Escolha a ração, informe a quantidade e a data para iniciar a produção."/><div className={styles.orderForm}><label>Escolha sua ração<select disabled={loading} value={formulaId} onChange={event=>setFormulaId(event.target.value)}>{loading?<option>Carregando...</option>:formulas.length?formulas.map(item=><option key={item.id} value={item.id}>{item.nome}</option>):<option value="">Nenhuma fórmula cadastrada</option>}</select></label><label>Quantidade produzida (kg)<input type="number" min="1" step="0.01" value={quantity} onChange={event=>setQuantity(Number(event.target.value||0))}/></label><label>Data da produção<div className={styles.dateInput}><input type="date" value={date} onChange={event=>setDate(event.target.value)}/><CalendarDays/></div></label><button onClick={produce} disabled={producing||!summary.enough}><Factory/>{producing?"Produzindo...":"Produzir Ração"}</button></div></section>
   <section className={styles.card}><SectionTitle number="2" title="Checklist de Ingredientes (Resumo Final)" text="Resumo dos ingredientes necessários para esta produção."/><div className={styles.tableWrap}><table><thead><tr><th>Ingrediente</th><th>Quantidade necessária</th><th>Estoque disponível</th><th>Custo por kg</th><th>Custo total</th><th>Status</th></tr></thead><tbody>{summary.items.length?summary.items.map(item=><tr key={item.id}><td><b>{item.item_nome}</b><small>{number(item.percentage)}% da fórmula</small></td><td>{number(item.required)} kg</td><td className={item.enough?styles.available:styles.missing}>{number(item.available)} kg</td><td>{money(item.unitCost)}</td><td>{money(item.totalCost)}</td><td><span data-ok={item.enough}>{item.enough?"Disponível":"Insuficiente"}</span></td></tr>):<tr><td colSpan={6} className={styles.empty}>Selecione uma fórmula com ingredientes cadastrados.</td></tr>}</tbody></table></div><div className={styles.totals}><Metric icon={Scale} label="Total necessário" value={`${number(quantity)} kg`} tone="blue"/><Metric icon={PackageOpen} label="Total disponível" value={`${number(summary.totalAvailable)} kg`} tone="green"/><Metric icon={CircleDollarSign} label="Custo total previsto" value={money(summary.totalCost)} tone="orange"/><Metric icon={Factory} label="Custo médio por kg" value={money(summary.costKg)} tone="purple"/></div></section>
   <section className={styles.card}><div className={styles.historyTitle}><SectionTitle number="3" title="Produções Realizadas" text="Histórico das produções de ração realizadas."/><span>{productions.length} registro(s)</span></div><div className={styles.tableWrap}><table><thead><tr><th>Data</th><th>Ração</th><th>Quantidade produzida</th><th>Custo por kg</th><th>Custo total</th><th>Usuário</th><th>Status</th></tr></thead><tbody>{productions.length?productions.slice(0,12).map(item=>{const produced=Number(item.quantidade_real),cost=Number(item.custo_total);return <tr key={item.id}><td>{new Date(item.data_producao).toLocaleDateString("pt-BR")}</td><td><b>{item.formula_nome}</b></td><td>{number(produced)} kg</td><td>{money(produced?cost/produced:0)}</td><td>{money(cost)}</td><td>{item.responsavel_nome||"-"}</td><td><span data-ok={item.status==="concluida"}>{item.status==="concluida"?"Concluída":item.status}</span></td></tr>}):<tr><td colSpan={7} className={styles.empty}>Nenhuma produção registrada.</td></tr>}</tbody></table></div></section>
  </main><aside>
   <section className={styles.finalCard}><Factory/><div><h2>Finalizar e Produzir</h2><p>Revise o checklist e confirme a produção da ração.</p></div><button onClick={produce} disabled={producing||!summary.enough}><Play/>{producing?"Produzindo...":"Produzir Ração"}</button>{!summary.enough&&<small>Verifique o estoque dos ingredientes</small>}</section>
   <section className={styles.info}><h2>Informações da Ração</h2><dl><dt>Ração</dt><dd>{formula?.nome||"Nenhuma selecionada"}</dd><dt>Descrição</dt><dd>{formula?.descricao||"Sem descrição cadastrada."}</dd><dt>Produto gerado</dt><dd>{formula?.item_final_nome||"Não informado"}</dd></dl></section>
   <section className={styles.tips}><h2>Dicas rápidas</h2>{["Verifique o estoque dos ingredientes antes de produzir.","Mantenha suas fórmulas sempre atualizadas.","Acompanhe o custo médio por kg para melhorar a gestão."].map(text=><p key={text}><Check/>{text}</p>)}</section>
  </aside></div>
 </div>;
}
function SectionTitle({number,title,text}:{number:string;title:string;text:string}){return <div className={styles.sectionTitle}><span>{number}.</span><div><h2>{title}</h2><p>{text}</p></div></div>}
function Metric({icon:Icon,label,value,tone}:{icon:typeof Boxes;label:string;value:string;tone:string}){return <article data-tone={tone}><Icon/><div><span>{label}</span><b>{value}</b></div></article>}
