# Generated by Django 5.2.13 on 2026-07-16 04:23

import django.db.models.deletion
from django.db import migrations, models


def populate_log_organizations(apps, schema_editor):
    AuditLog = apps.get_model('audit', 'AuditLog')
    for log in AuditLog.objects.filter(user__organization__isnull=False).select_related('user'):
        log.organization_id = log.user.organization_id
        log.save(update_fields=['organization'])


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('organizations', '0002_organizationaddress_organizationcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_audit_logs', to='organizations.organization'),
        ),
        migrations.RunPython(populate_log_organizations, migrations.RunPython.noop),
    ]
