# Generated by Django 5.2.13 on 2026-07-16 04:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('corral', 'Curral'), ('pigsty', 'Chiqueiro'), ('poultry_house', 'Galinheiro'), ('warehouse', 'Depósitos e armazéns'), ('irrigation', 'Irrigação'), ('water_reservoir', 'Reservatórios e água'), ('facility', 'Instalações'), ('fence', 'Cercas e divisões'), ('other', 'Outros')], max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('acquisition_value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farm_structures_created', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='farms.farm')),
            ],
            options={
                'verbose_name': 'Farm structure',
                'verbose_name_plural': 'Farm structures',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['farm', 'category', 'is_active'], name='farms_farms_farm_id_8aa426_idx')],
            },
        ),
    ]
