# Generated by Django 5.2.13 on 2026-07-16 05:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_farmstructure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.CharField(choices=[('tractor', 'Trator'), ('harvester', 'Colheitadeira'), ('planter', 'Plantadeira'), ('sprayer', 'Pulverizador'), ('truck', 'Caminhão'), ('pickup', 'Caminhonete'), ('car', 'Automóvel'), ('motorcycle', 'Motocicleta'), ('other', 'Outro')], max_length=20)),
                ('brand', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=100)),
                ('manufacture_year', models.PositiveIntegerField(blank=True, null=True)),
                ('fuel', models.CharField(blank=True, max_length=40)),
                ('traction', models.CharField(blank=True, max_length=40)),
                ('current_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                ('power', models.CharField(blank=True, max_length=60)),
                ('tank_capacity_l', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('transmission', models.CharField(blank=True, max_length=100)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('acquisition_value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farm_assets_created', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agricultural_assets', to='farms.farm')),
            ],
            options={
                'verbose_name': 'Agricultural machine or vehicle',
                'verbose_name_plural': 'Agricultural machines and vehicles',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FarmAssetImplement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('brand_model', models.CharField(blank=True, max_length=150)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('manufacture_year', models.PositiveIntegerField(blank=True, null=True)),
                ('acquisition_value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implements', to='farms.farmasset')),
            ],
            options={
                'verbose_name': 'Agricultural implement',
                'verbose_name_plural': 'Agricultural implements',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='farmasset',
            index=models.Index(fields=['farm', 'asset_type', 'is_active'], name='farms_farma_farm_id_a47ad9_idx'),
        ),
    ]
