# Generated by Django 5.2.13 on 2026-07-16 05:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_farmasset_farmassetimplement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmstructure',
            name='built_area_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='farmstructure',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='farmstructure',
            name='length_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='farmstructure',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='farmstructure',
            name='width_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='FarmStructureItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit', models.CharField(default='un', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='farms.farmstructure')),
            ],
            options={
                'verbose_name': 'Farm structure item',
                'verbose_name_plural': 'Farm structure items',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
