# Generated by Django 5.2.13 on 2026-04-19 15:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('area_ha', models.DecimalField(decimal_places=2, max_digits=10)),
                ('soil_type', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='farms.farm')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='farms.sector')),
            ],
            options={
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlantingCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_name', models.CharField(help_text='e.g. Soja, Milho, Cana-de-açúcar', max_length=100)),
                ('variety', models.CharField(blank=True, max_length=100)),
                ('planting_date', models.DateField()),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('planting', 'Planting'), ('growing', 'Growing'), ('harvesting', 'Harvesting'), ('finished', 'Finished')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planting_cycles', to='crops.field')),
            ],
            options={
                'verbose_name': 'Planting Cycle',
                'verbose_name_plural': 'Planting Cycles',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('harvest_date', models.DateField()),
                ('yield_kg', models.DecimalField(decimal_places=2, max_digits=14)),
                ('yield_per_ha_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quality_grade', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('planting_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='crops.plantingcycle')),
            ],
            options={
                'verbose_name': 'Harvest',
                'verbose_name_plural': 'Harvests',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
