# Generated by Django 5.2.14 on 2026-06-11 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
        ('farms', '0001_initial'),
        ('organizations', '0002_organizationaddress_organizationcontact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantingcycle',
            options={'ordering': ['-created_at'], 'verbose_name': 'Plantação', 'verbose_name_plural': 'Plantações'},
        ),
        migrations.AddField(
            model_name='field',
            name='estimated_yield_capacity_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='irrigation_type',
            field=models.CharField(blank=True, help_text='e.g. pivot, drip, flood', max_length=50),
        ),
        migrations.AddField(
            model_name='field',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plantingcycle',
            name='actual_harvest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantingcycle',
            name='crop_type',
            field=models.CharField(choices=[('grain', 'Grão'), ('fruit', 'Fruta'), ('vegetable', 'Legume'), ('forage', 'Forragem'), ('fiber', 'Fibra'), ('other', 'Outro')], default='grain', max_length=20),
        ),
        migrations.AddField(
            model_name='plantingcycle',
            name='estimated_bags',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plantingcycle',
            name='estimated_production_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='plantingcycle',
            name='estimated_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='plantingcycle',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantations', to='farms.farm'),
        ),
        migrations.AddField(
            model_name='plantingcycle',
            name='hybrid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plantingcycle',
            name='name',
            field=models.CharField(blank=True, help_text='Friendly name, e.g. Milho Safra 2025.2', max_length=255),
        ),
        migrations.AddField(
            model_name='plantingcycle',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantations', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='plantingcycle',
            name='planted_area_ha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plantingcycle',
            name='population',
            field=models.PositiveIntegerField(blank=True, help_text='Plants per hectare', null=True),
        ),
        migrations.AddField(
            model_name='plantingcycle',
            name='responsible_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_plantations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plantingcycle',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantations', to='farms.sector'),
        ),
        migrations.AddField(
            model_name='plantingcycle',
            name='spacing',
            field=models.CharField(blank=True, help_text='e.g. 0.5m x 0.3m', max_length=100),
        ),
        migrations.AlterField(
            model_name='plantingcycle',
            name='status',
            field=models.CharField(choices=[('planned', 'Planejada'), ('planting', 'Em plantio'), ('growing', 'Em desenvolvimento'), ('management', 'Em manejo'), ('harvesting', 'Em colheita'), ('finished', 'Finalizada'), ('cancelled', 'Cancelada')], default='planned', max_length=20),
        ),
    ]
