# Generated by Django 5.2.14 on 2026-06-11 03:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_alter_plantingcycle_options_and_more'),
        ('inventory', '0019_itemestoque_tipo_semen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('quantity_per_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('population', models.PositiveIntegerField(blank=True, help_text='Plants per hectare', null=True)),
                ('spacing', models.CharField(blank=True, max_length=100)),
                ('depth', models.CharField(blank=True, help_text='Planting depth', max_length=50)),
                ('planting_date', models.DateField()),
                ('operator', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crop_plantings', to='inventory.itemestoque')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_plantings', to='inventory.loteestoque')),
                ('plantation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantings', to='crops.plantingcycle')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_plantings', to='inventory.fornecedor')),
            ],
            options={
                'verbose_name': 'Planting',
                'verbose_name_plural': 'Plantings',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
