# Generated by Django 5.2.14 on 2026-06-11 03:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_add_planting_model_and_transaction_fk'),
        ('inventory', '0019_itemestoque_tipo_semen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertigation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('syrup_liters', models.DecimalField(blank=True, decimal_places=2, help_text='Litros de calda', max_digits=12, null=True)),
                ('concentration', models.CharField(blank=True, help_text='Concentração / diluição', max_length=100)),
                ('application_time_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('area_applied_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('application_date', models.DateField()),
                ('operator', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crop_fertigations', to='inventory.itemestoque')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_fertigations', to='inventory.loteestoque')),
                ('plantation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertigations', to='crops.plantingcycle')),
            ],
            options={
                'verbose_name': 'Fertigation',
                'verbose_name_plural': 'Fertigations',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fertilization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('dose_per_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('application_method', models.CharField(choices=[('broadcast', 'Lanço'), ('row', 'Sulco'), ('foliar', 'Foliar'), ('soil_injection', 'Injeção no solo'), ('other', 'Outro')], default='broadcast', max_length=30)),
                ('area_applied_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('application_date', models.DateField()),
                ('operator', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crop_fertilizations', to='inventory.itemestoque')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_fertilizations', to='inventory.loteestoque')),
                ('plantation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizations', to='crops.plantingcycle')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_fertilizations', to='inventory.fornecedor')),
            ],
            options={
                'verbose_name': 'Fertilization',
                'verbose_name_plural': 'Fertilizations',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PesticideApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pesticide_type', models.CharField(choices=[('insecticide', 'Inseticida'), ('herbicide', 'Herbicida'), ('fungicide', 'Fungicida'), ('adjuvant', 'Adjuvante'), ('acaricide', 'Acaricida'), ('bactericide', 'Bactericida'), ('other', 'Outro')], default='other', max_length=30)),
                ('active_ingredient', models.CharField(blank=True, max_length=200)),
                ('dose', models.CharField(blank=True, help_text='e.g. 0.5 L/ha', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('area_applied_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('application_date', models.DateField()),
                ('operator', models.CharField(blank=True, max_length=150)),
                ('target', models.CharField(blank=True, help_text='Alvo da aplicação (praga/doença)', max_length=200)),
                ('equipment', models.CharField(blank=True, max_length=150)),
                ('withholding_days', models.PositiveIntegerField(blank=True, help_text='Carência (dias)', null=True)),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crop_pesticide_applications', to='inventory.itemestoque')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_pesticide_applications', to='inventory.loteestoque')),
                ('plantation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesticide_applications', to='crops.plantingcycle')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_pesticide_applications', to='inventory.fornecedor')),
            ],
            options={
                'verbose_name': 'Pesticide Application',
                'verbose_name_plural': 'Pesticide Applications',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
