# Generated by Django 5.2.14 on 2026-06-11 03:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0004_add_fertilization_fertigation_pesticide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Irrigation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('pump', models.CharField(blank=True, help_text='Bomba utilizada', max_length=150)),
                ('pump_power_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('hours', models.DecimalField(blank=True, decimal_places=2, help_text='Tempo ligado (horas)', max_digits=8, null=True)),
                ('flow_rate_l_per_h', models.DecimalField(blank=True, decimal_places=2, help_text='Vazão (L/h)', max_digits=12, null=True)),
                ('liters_used', models.DecimalField(blank=True, decimal_places=2, help_text='Litros utilizados (calculado)', max_digits=14, null=True)),
                ('energy_kwh', models.DecimalField(blank=True, decimal_places=2, help_text='Energia consumida kWh (calculado)', max_digits=12, null=True)),
                ('kwh_value', models.DecimalField(blank=True, decimal_places=4, help_text='Valor do kWh (R$)', max_digits=10, null=True)),
                ('energy_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Custo energético (R$, calculado)', max_digits=14, null=True)),
                ('operator', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('plantation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigations', to='crops.plantingcycle')),
            ],
            options={
                'verbose_name': 'Irrigation',
                'verbose_name_plural': 'Irrigations',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
