# Generated by Django 5.2.14 on 2026-06-19 01:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0006_plantingcycle_seed_quantity_used'),
        ('organizations', '0002_organizationaddress_organizationcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tractor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('power_cv', models.PositiveIntegerField(blank=True, help_text='Potência em CV', null=True)),
                ('plate', models.CharField(blank=True, help_text='Placa ou identificação', max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tractors', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Trator',
                'verbose_name_plural': 'Tratores',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandPreparation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('operation_type', models.CharField(choices=[('calagem', 'Calagem'), ('aracao', 'Aração'), ('gradagem', 'Gradagem'), ('subsolagem', 'Subsolagem'), ('nivelamento', 'Nivelamento'), ('rocagem', 'Roçagem'), ('outro', 'Outro')], default='outro', max_length=30)),
                ('execution_type', models.CharField(choices=[('own', 'Equipamento próprio'), ('rented', 'Terceirizado')], default='own', max_length=20)),
                ('hours_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fuel_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fuel_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('operator', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('plantation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_preparations', to='crops.plantingcycle')),
                ('tractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='land_preparations', to='crops.tractor')),
            ],
            options={
                'verbose_name': 'Preparação de Terra',
                'verbose_name_plural': 'Preparações de Terra',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
