# Generated by Codex on 2026-06-19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crops", "0007_tractor_landpreparation"),
        ("organizations", "0002_organizationaddress_organizationcontact"),
    ]

    operations = [
        migrations.CreateModel(
            name="IrrigationPump",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("power_cv", models.DecimalField(decimal_places=2, help_text="Potência em CV", max_digits=8)),
                ("power_kw", models.DecimalField(decimal_places=2, help_text="Potência convertida em kW", max_digits=8)),
                ("flow_rate_l_per_h", models.DecimalField(decimal_places=2, help_text="Vazão em L/h", max_digits=12)),
                ("is_active", models.BooleanField(default=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="irrigation_pumps", to="organizations.organization")),
            ],
            options={
                "verbose_name": "Bomba de Irrigação",
                "verbose_name_plural": "Bombas de Irrigação",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="irrigation",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="irrigation",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="irrigation",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="irrigation",
            name="irrigation_system",
            field=models.CharField(blank=True, choices=[("center_pivot", "Pivô central"), ("drip", "Gotejamento"), ("sprinkler", "Aspersão"), ("micro_sprinkler", "Microaspersão"), ("hose", "Mangueira"), ("other", "Outro")], max_length=30),
        ),
        migrations.AddField(
            model_name="irrigation",
            name="hours_per_day",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name="irrigation",
            name="operating_days",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="irrigation",
            name="pump_equipment",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="irrigations", to="crops.irrigationpump"),
        ),
    ]
