# Generated by Codex on 2026-06-19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crops", "0008_irrigation_pumps_and_period"),
        ("inventory", "0019_itemestoque_tipo_semen"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgronomistRecommendation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("objective", models.TextField(blank=True)),
                ("recommendation_date", models.DateField()),
                ("suggested_application_date", models.DateField(blank=True, null=True)),
                ("priority", models.CharField(choices=[("low", "Baixa"), ("medium", "Média"), ("high", "Alta")], default="medium", max_length=20)),
                ("status", models.CharField(choices=[("pending", "Pendente"), ("in_progress", "Em execução"), ("completed", "Concluída")], default="pending", max_length=20)),
                ("area_ha", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="agronomist_recommendations_created", to=settings.AUTH_USER_MODEL)),
                ("field", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="agronomist_recommendations", to="crops.field")),
                ("plantation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="agronomist_recommendations", to="crops.plantingcycle")),
            ],
            options={
                "verbose_name": "Recomendação do Agrônomo",
                "verbose_name_plural": "Recomendações do Agrônomo",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SoilAnalysis",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="crops/soil_analyses/%Y/%m/")),
                ("original_name", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("field", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="soil_analyses", to="crops.field")),
                ("plantation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="soil_analyses", to="crops.plantingcycle")),
                ("uploaded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="soil_analyses_uploaded", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Análise de Solo",
                "verbose_name_plural": "Análises de Solo",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AgronomistRecommendationProduct",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dose_per_ha", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("dose_unit", models.CharField(blank=True, max_length=20)),
                ("total_quantity", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("total_unit", models.CharField(blank=True, max_length=20)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="agronomist_recommendation_products", to="inventory.itemestoque")),
                ("recommendation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="products", to="crops.agronomistrecommendation")),
            ],
            options={
                "verbose_name": "Produto Recomendado",
                "verbose_name_plural": "Produtos Recomendados",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
