# Generated by Django 5.2.14 on 2026-06-23 00:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0009_agronomist_area'),
        ('organizations', '0002_organizationaddress_organizationcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborWorker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('worker_type', models.CharField(choices=[('employee', 'Funcionário'), ('provider', 'Prestador')], default='employee', max_length=20)),
                ('document', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_workers', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Trabalhador',
                'verbose_name_plural': 'Trabalhadores',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LaborRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('land_preparation', 'Preparo de terra'), ('planting', 'Plantio'), ('fertilization', 'Adubação'), ('fertigation', 'Fertirrigação'), ('pesticide_application', 'Aplicação de Defensivos'), ('irrigation', 'Irrigação'), ('harvest', 'Colheita'), ('other', 'Outro')], default='other', max_length=40)),
                ('payment_method', models.CharField(choices=[('daily', 'Por diária')], default='daily', max_length=20)),
                ('activity_date', models.DateField()),
                ('daily_quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('plantation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_records', to='crops.plantingcycle')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labor_records', to='crops.laborworker')),
            ],
            options={
                'verbose_name': 'Lançamento de Mão de Obra',
                'verbose_name_plural': 'Lançamentos de Mão de Obra',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='laborworker',
            index=models.Index(fields=['organization', 'name'], name='crops_labor_organiz_7ca35e_idx'),
        ),
        migrations.AddIndex(
            model_name='laborworker',
            index=models.Index(fields=['organization', 'is_active'], name='crops_labor_organiz_8f3a24_idx'),
        ),
        migrations.AddIndex(
            model_name='laborrecord',
            index=models.Index(fields=['plantation', 'activity_date'], name='crops_labor_plantat_73414c_idx'),
        ),
        migrations.AddIndex(
            model_name='laborrecord',
            index=models.Index(fields=['worker', 'activity_date'], name='crops_labor_worker__8d7d32_idx'),
        ),
    ]
