# Generated by Django 5.2.14 on 2026-06-23 01:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0010_laborworker_laborrecord_and_more'),
        ('organizations', '0002_organizationaddress_organizationcontact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harvest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Colheita', 'verbose_name_plural': 'Colheitas'},
        ),
        migrations.AddField(
            model_name='harvest',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='harvest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='harvest',
            name='destination',
            field=models.CharField(choices=[('sale', 'Venda'), ('stock', 'Estoque'), ('own_use', 'Uso próprio'), ('seed', 'Semente'), ('other', 'Outro')], default='sale', max_length=20),
        ),
        migrations.AddField(
            model_name='harvest',
            name='harvest_type',
            field=models.CharField(choices=[('partial', 'Parcial'), ('total', 'Total')], default='partial', max_length=20),
        ),
        migrations.AddField(
            model_name='harvest',
            name='revenue_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='harvest',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='HarvestBuyer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('document', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_buyers', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Comprador de Colheita',
                'verbose_name_plural': 'Compradores de Colheita',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='harvest',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvests', to='crops.harvestbuyer'),
        ),
        migrations.AddIndex(
            model_name='harvest',
            index=models.Index(fields=['planting_cycle', 'harvest_date'], name='crops_harve_plantin_9d336b_idx'),
        ),
        migrations.AddIndex(
            model_name='harvest',
            index=models.Index(fields=['destination', 'harvest_date'], name='crops_harve_destina_ca825b_idx'),
        ),
        migrations.AddIndex(
            model_name='harvestbuyer',
            index=models.Index(fields=['organization', 'name'], name='crops_harve_organiz_0fe865_idx'),
        ),
        migrations.AddIndex(
            model_name='harvestbuyer',
            index=models.Index(fields=['organization', 'is_active'], name='crops_harve_organiz_91de41_idx'),
        ),
    ]
