# Generated by Django 5.2.15 on 2026-07-03 15:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0011_alter_harvest_options_harvest_buyer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesticideApplicationEquipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.CharField(max_length=150)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='crops.pesticideapplication')),
            ],
            options={
                'verbose_name': 'Pesticide Application Equipment',
                'verbose_name_plural': 'Pesticide Application Equipments',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
