# Generated by Django 5.2.13 on 2026-08-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0013_sectorstructureitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertigation',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='fertilization',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='pesticideapplication',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='pesticideapplicationequipment',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='planting',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
