# Generated by Django 5.2.14 on 2026-06-11 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_add_planting_model_and_transaction_fk'),
        ('finance', '0002_transaction_attachment_transaction_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='planting_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transactions', to='crops.plantingcycle'),
        ),
    ]
