# Generated by Django 5.2.15 on 2026-08-21 21:57

import apps.affiliates.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0004_subscription_discounts'),
        ('organizations', '0002_organizationaddress_organizationcontact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, default=apps.affiliates.models.generate_affiliate_code, editable=False, max_length=24, unique=True)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], db_index=True, default='active', max_length=20)),
                ('commission_type', models.CharField(choices=[('percentage', 'Percentual'), ('fixed_amount', 'Valor fixo')], default='percentage', max_length=20)),
                ('commission_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_affiliate_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de afiliado',
                'verbose_name_plural': 'Perfis de afiliados',
                'ordering': ('user__full_name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('commission_type_snapshot', models.CharField(choices=[('percentage', 'Percentual'), ('fixed_amount', 'Valor fixo')], max_length=20)),
                ('commission_rate_snapshot', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('conversion_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('paid', 'Paga'), ('cancelled', 'Cancelada/estornada')], db_index=True, default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('status_reason', models.TextField(blank=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='affiliates.affiliateprofile')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_affiliate_commissions', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_affiliate_commissions', to=settings.AUTH_USER_MODEL)),
                ('customer_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affiliate_commissions_as_customer', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='affiliate_commission', to='billing.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affiliate_commissions', to='organizations.organization')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_affiliate_commissions', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='affiliate_commissions', to='billing.payment')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affiliate_commissions', to='billing.plan')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affiliate_commissions', to='billing.subscription')),
            ],
            options={
                'ordering': ('-conversion_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommissionStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('paid', 'Paga'), ('cancelled', 'Cancelada/estornada')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_commission_status_changes', to=settings.AUTH_USER_MODEL)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='affiliates.commission')),
            ],
            options={
                'verbose_name': 'Histórico de status de comissão',
                'verbose_name_plural': 'Históricos de status de comissões',
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReferralAttribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor_id', models.UUIDField(db_index=True)),
                ('attributed_at', models.DateTimeField(db_index=True)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('visited', 'Visitou'), ('registered', 'Cadastrado'), ('converted', 'Convertido'), ('invalidated', 'Invalidado')], db_index=True, default='visited', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributions', to='affiliates.affiliateprofile')),
                ('organization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referral_attribution', to='organizations.organization')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referral_attribution', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-attributed_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='commission',
            name='attribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='affiliates.referralattribution'),
        ),
        migrations.CreateModel(
            name='ReferralVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('landing_path', models.CharField(blank=True, max_length=500)),
                ('referrer', models.URLField(blank=True, max_length=1000)),
                ('utm_source', models.CharField(blank=True, max_length=120)),
                ('utm_medium', models.CharField(blank=True, max_length=120)),
                ('utm_campaign', models.CharField(blank=True, max_length=120)),
                ('ip_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='affiliates.affiliateprofile')),
            ],
            options={
                'ordering': ('-occurred_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='referralattribution',
            name='first_visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='first_touch_attributions', to='affiliates.referralvisit'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['affiliate', 'status'], name='aff_comm_aff_status_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['organization', 'conversion_at'], name='aff_comm_org_time_idx'),
        ),
        migrations.AddIndex(
            model_name='referralvisit',
            index=models.Index(fields=['affiliate', 'occurred_at'], name='aff_visit_aff_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='referralattribution',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'invalidated'), _negated=True), fields=('visitor_id',), name='unique_active_visitor_attribution'),
        ),
    ]
