# Generated by Django 5.2.15 on 2026-08-22 11:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0001_initial'),
        ('billing', '0004_subscription_discounts'),
        ('organizations', '0002_organizationaddress_organizationcontact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='commission',
            constraint=models.UniqueConstraint(fields=('organization',), name='unique_first_customer_commission'),
        ),
    ]
