# Generated by Django 5.2.15 on 2026-08-22 11:51

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0002_commission_unique_first_customer_commission'),
        ('billing', '0004_subscription_discounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjustment_type', models.CharField(choices=[('reversal', 'Estorno')], default='reversal', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reason', models.TextField()),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='affiliates.commission')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_commission_adjustments', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='affiliate_commission_adjustment', to='billing.payment')),
            ],
            options={
                'verbose_name': 'Ajuste de comissão',
                'verbose_name_plural': 'Ajustes de comissões',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
