# Generated by Django 5.2.15 on 2026-08-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0003_commissionadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateprofile',
            name='portal_access_only',
            field=models.BooleanField(default=False, help_text='Permite somente o acesso ao portal dedicado de afiliados.'),
        ),
    ]
