# Generated by Django 5.2.15 on 2026-08-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0004_affiliateprofile_portal_access_only'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='commission',
            name='unique_first_customer_commission',
        ),
        migrations.AddField(
            model_name='affiliateprofile',
            name='commission_duration',
            field=models.CharField(choices=[('first_payment', 'Primeira mensalidade'), ('first_three_payments', '3 primeiras mensalidades'), ('permanent', 'Permanente')], default='first_payment', max_length=30),
        ),
        migrations.AddField(
            model_name='commission',
            name='commission_duration_snapshot',
            field=models.CharField(choices=[('first_payment', 'Primeira mensalidade'), ('first_three_payments', '3 primeiras mensalidades'), ('permanent', 'Permanente')], default='first_payment', max_length=30),
        ),
    ]
