import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BarChart3, Beef, Boxes, CheckCircle2, HeartPulse, ShieldCheck, Users, WalletCards, Wheat } from "lucide-react";
import { MarketingPage } from "@/components/marketing/MarketingPage";

export const metadata: Metadata = { title:"Recursos | AgroManage", description:"Conheça em detalhes os módulos de gestão rural do AgroManage." };
const modules=[
  {Icon:Wheat,title:"Plantações",tag:"Produção agrícola",text:"Acompanhe o ciclo produtivo do preparo à colheita, mantendo custos e atividades ligados à área correta.",items:["Preparo de solo, adubação e sementes","Irrigação, defensivos e fertirrigação","Mão de obra, agrônomo, histórico e colheita"]},
  {Icon:Beef,title:"Rebanhos",tag:"Produção animal",text:"Organize animais e lotes com informações produtivas, reprodutivas, alimentares e sanitárias.",items:["Suínos, aves e bovinos","Cadastros, lotes, pesagens e reprodução","Consumo e fórmulas de ração"]},
  {Icon:Boxes,title:"Estoque",tag:"Suprimentos",text:"Tenha visibilidade das entradas, saídas e necessidades de reposição dos itens utilizados na operação.",items:["Produtos, fornecedores e movimentações","Alertas de estoque mínimo","Produção de ração integrada"]},
  {Icon:WalletCards,title:"Financeiro",tag:"Resultados",text:"Centralize registros financeiros e acompanhe como a operação se transforma em receitas, despesas e resultado.",items:["Receitas e despesas organizadas","Visão consolidada da organização","Base para relatórios gerenciais"]},
  {Icon:HeartPulse,title:"Clínica veterinária",tag:"Saúde animal",text:"Mantenha registros clínicos conectados ao histórico do rebanho e disponíveis para acompanhamento.",items:["Consultas e exames","Medicamentos e vacinação","Histórico sanitário organizado"]},
  {Icon:BarChart3,title:"Relatórios",tag:"Inteligência",text:"Reúna os dados cadastrados em indicadores que ajudam a comparar períodos e encontrar prioridades.",items:["Visões gerais e específicas","Relatórios financeiros, de estoque e rebanho","Dados contextualizados por organização"]},
] as const;
export default function RecursosPage(){return <MarketingPage eyebrow="Recursos" title="Tudo que sua operação precisa, conectado" description="Conheça como cada módulo transforma atividades do campo em informação organizada e acionável."><section className="resource-nav"><div className="marketing-container">{modules.map(({Icon,title})=><a href={`#${title.toLowerCase().replace("ó","o")}`} key={title}><Icon size={18}/>{title}</a>)}</div></section><section className="resource-modules"><div className="marketing-container">{modules.map(({Icon,title,tag,text,items},index)=><article className="resource-row" id={title.toLowerCase().replace("ó","o")} key={title}><div className="resource-number">0{index+1}</div><div className="resource-heading"><div className="feature-icon"><Icon size={23}/></div><span>{tag}</span><h2>{title}</h2></div><div className="resource-detail"><p>{text}</p><ul>{items.map(item=><li key={item}><CheckCircle2 size={17}/>{item}</li>)}</ul></div></article>)}</div></section><section className="resource-security"><div className="marketing-container resource-security-grid"><div><ShieldCheck size={34}/><h2>Controle também significa saber quem pode fazer o quê</h2><p>Permissões por papel, isolamento entre organizações e registros administrativos ajudam a proteger a rotina da sua equipe.</p></div><div><Users size={34}/><h2>Uma visão para cada responsabilidade</h2><p>Proprietários, administradores, gestores, operadores e visualizadores trabalham no mesmo ambiente com acessos adequados.</p></div></div></section><section className="resource-cta"><div className="marketing-container"><h2>Veja esses recursos aplicados à sua realidade</h2><p>Uma demonstração orientada ajuda a identificar os módulos e o plano mais adequados.</p><Link href="/contato" className="marketing-button primary">Solicitar demonstração <ArrowRight size={17}/></Link></div></section></MarketingPage>}
