# Generated by Codex on 2026-06-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_force_password_change"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="default_unit",
            field=models.CharField(default="kg", max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="email_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="min_stock_alert",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="user",
            name="stock_alerts",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="theme",
            field=models.CharField(
                choices=[
                    ("light", "Padrão"),
                    ("dark", "Escuro"),
                    ("contrast", "Alto contraste"),
                ],
                default="light",
                max_length=20,
            ),
        ),
    ]
