# Generated by Django 5.2.17 on 2026-10-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_session_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Proprietário'), ('admin', 'Administrador'), ('manager', 'Gerente'), ('operator', 'Operador'), ('viewer', 'Visualizador')], default='operator', max_length=20),
        ),
    ]
