"use client";
import React,{useCallback,useEffect,useMemo,useState} from "react";
import {Activity,AlertTriangle,BarChart3,BadgeDollarSign,CalendarDays,Coins,Download,FileSpreadsheet,Filter,HeartPulse,LoaderCircle,Percent,PiggyBank,Printer,Search,TrendingUp,UsersRound} from "lucide-react";
import * as XLSX from "xlsx";
import {jsPDF} from "jspdf";
import autoTable from "jspdf-autotable";
import apiClient from "@/services/api";
import styles from "./page.module.css";

type Tab="overview"|"reproduction"|"batches"|"females";
type DataSource="inventory"|"transactions"|"animals"|"reproduction";
interface Item{id:string;batch_code:string;name?:string;quantity:number;category?:string;breed?:string;farm:string;entry_date?:string;status:string;avg_weight?:number;species_code:string}
interface Report{total_animals:number;total_active_animals:number;items:Item[];by_status:{status:string;total:number;batches:number}[]}
interface Transaction{id:string;description:string;amount:string;due_date:string;payment_date?:string;status:string;category_name:string;category_type:"revenue"|"expense";reference?:string}
interface ReproductiveCycle{mating_date?:string;expected_birth_date?:string;live_born?:number;stillborn?:number;mummified?:number;total_born?:number;mortality?:number;avg_birth_weight_kg?:number;weaned_quantity?:number;avg_weaning_weight_kg?:number;weaning_date?:string;lactation_days?:number;gestation_days?:number;pregnancy_confirmed?:boolean;pregnancy_status?:string;birth_date?:string}
interface Female{id:string;farm:string;farm_name?:string;identifier:string;category:string;reproductive_status:string;birth_count:number;birth_date?:string;breed_name?:string;status:string;reproductive_cycles?:ReproductiveCycle[]}
interface Repro{kpis:{marras:number;matrizes_ativas:number;reprodutores:number;gestantes:number;aguardando_cobertura:number;nascidos_mes:number;tx_prenhez:string}}
const brl=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}),num=new Intl.NumberFormat("pt-BR");
const today=()=>new Date().toISOString().slice(0,10),monthStart=()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth(),1).toISOString().slice(0,10)};
const tabs=[{id:"overview" as Tab,label:"Visão Geral",Icon:BarChart3},{id:"reproduction" as Tab,label:"Índices Reprodutivos",Icon:HeartPulse},{id:"batches" as Tab,label:"Relatório Geral dos Lotes",Icon:FileSpreadsheet},{id:"females" as Tab,label:"Relatório das Matrizes",Icon:UsersRound}];
const dataSources:DataSource[]=["inventory","transactions","animals","reproduction"];
const sourceLabels:Record<DataSource,string>={inventory:"inventário do rebanho",transactions:"dados financeiros",animals:"matrizes",reproduction:"índices reprodutivos"};
const initialPending:Record<DataSource,boolean>={inventory:true,transactions:true,animals:true,reproduction:true};
const initialErrors:Record<DataSource,string|null>={inventory:null,transactions:null,animals:null,reproduction:null};

export default function SwineReports(){const [tab,setTab]=useState<Tab>("overview"),[report,setReport]=useState<Report|null>(null),[transactions,setTransactions]=useState<Transaction[]>([]),[females,setFemales]=useState<Female[]>([]),[repro,setRepro]=useState<Repro|null>(null),[pending,setPending]=useState(initialPending),[errors,setErrors]=useState(initialErrors),[from,setFrom]=useState(monthStart()),[to,setTo]=useState(today()),[status,setStatus]=useState(""),[category,setCategory]=useState(""),[search,setSearch]=useState("");
 const load=useCallback(async(sources:DataSource[],signal?:AbortSignal)=>{setPending(current=>({...current,...Object.fromEntries(sources.map(source=>[source,true]))}));setErrors(current=>({...current,...Object.fromEntries(sources.map(source=>[source,null]))}));await Promise.allSettled(sources.map(async source=>{try{if(source==="inventory"){const response=await apiClient.get<Report>("/reports/livestock/inventory/",{params:{species:"suinos"},signal});setReport(response.data)}else if(source==="transactions"){const response=await apiClient.get("/finance/transactions/",{params:{page_size:1000},signal});setTransactions(response.data.results||response.data||[])}else if(source==="animals"){const response=await apiClient.get("/livestock/animals/",{params:{species:"suinos",page_size:1000},signal});const animals:Female[]=response.data.results||response.data||[];setFemales(animals.filter(x=>x.category==="Matriz"||x.category==="Marrã"))}else{const response=await apiClient.get<Repro>("/livestock/dashboard/reproduction/",{params:{species:"suinos"},signal});setRepro(response.data)}}catch{if(!signal?.aborted)setErrors(current=>({...current,[source]:`Não foi possível carregar ${sourceLabels[source]}.`}))}finally{if(!signal?.aborted)setPending(current=>({...current,[source]:false}))}}))},[]);
 useEffect(()=>{const controller=new AbortController();void Promise.resolve().then(()=>load(dataSources,controller.signal));return()=>controller.abort()},[load]);
 const periodTx=useMemo(()=>transactions.filter(x=>x.status==="paid"&&!!x.payment_date&&x.payment_date>=from&&x.payment_date<=to&&isLivestockTransaction(x)),[transactions,from,to]);const revenue=periodTx.filter(x=>x.category_type==="revenue").reduce((s,x)=>s+Number(x.amount),0),cost=periodTx.filter(x=>x.category_type==="expense").reduce((s,x)=>s+Number(x.amount),0),profit=revenue-cost,margin=revenue?profit/revenue*100:0,total=report?.total_active_animals||0;
 const filteredLots=useMemo(()=>(report?.items||[]).filter(x=>(!status||x.status===status)&&(!category||x.category===category)&&(!search||`${x.batch_code} ${x.name||""} ${x.farm}`.toLowerCase().includes(search.toLowerCase()))),[report,status,category,search]);const filteredFemales=useMemo(()=>females.filter(x=>(!status||x.status===status)&&(!search||x.identifier.toLowerCase().includes(search.toLowerCase()))),[females,status,search]);
 const costs=useMemo(()=>{const map=new Map<string,number>();periodTx.filter(x=>x.category_type==="expense").forEach(x=>map.set(x.category_name||"Outros",(map.get(x.category_name||"Outros")||0)+Number(x.amount)));return [...map].sort((a,b)=>b[1]-a[1])},[periodTx]);
 const rows=tab==="females"?filteredFemales.map(x=>[x.identifier,x.category,x.reproductive_status||"-",x.birth_count,x.breed_name||"-",x.status]):filteredLots.map(x=>[x.batch_code,x.quantity,x.category||"-",x.farm,x.entry_date||"-",x.status]);
 const exportExcel=()=>{const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([["Relatório","Suinocultura"],["Período",`${from} a ${to}`],["Custo",cost],["Receita",revenue],["Lucro",profit]]),"Resumo");XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([tab==="females"?["Matriz","Categoria","Fase","Partos","Raça","Status"]:["Lote","Quantidade","Categoria","Fazenda","Entrada","Status"],...rows]),tab==="females"?"Matrizes":"Lotes");XLSX.writeFile(wb,"relatorio_suinocultura.xlsx")};
 const exportPdf=()=>{const doc=new jsPDF({orientation:"landscape"});doc.setFontSize(18);doc.text("Relatório da Suinocultura",14,18);doc.setFontSize(9);doc.text(`Período: ${new Date(from+"T00:00:00").toLocaleDateString("pt-BR")} a ${new Date(to+"T00:00:00").toLocaleDateString("pt-BR")}`,14,25);autoTable(doc,{startY:31,head:[tab==="females"?["Matriz","Categoria","Fase","Partos","Raça","Status"]:["Lote","Qtd.","Categoria","Fazenda","Entrada","Status"]],body:rows});doc.save("relatorio_suinocultura.pdf")};
 const reset=()=>{setStatus("");setCategory("");setSearch("");setFrom(monthStart());setTo(today())};
 const failedSources=dataSources.filter(source=>errors[source]);const loadingSources=dataSources.filter(source=>pending[source]);
 return <div className={styles.page}><header className={styles.header}><div><span className={styles.pig}>🐖</span><div><h1>SUINOCULTURA</h1><p>Acompanhe o desempenho financeiro e produtivo da sua granja.</p></div></div><div className={styles.actions}><label><CalendarDays size={17}/><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/><span>até</span><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button onClick={exportExcel}><FileSpreadsheet size={17}/>Exportar Excel</button><button onClick={exportPdf}><Download size={17}/>Exportar PDF</button><button className={styles.print} onClick={()=>window.print()}><Printer size={17}/>Imprimir</button></div></header>
 <div className={`${styles.dataStatus} ${failedSources.length?styles.dataError:""}`} aria-live="polite">{failedSources.length?<><AlertTriangle size={18}/><span>{failedSources.map(source=>errors[source]).join(" ")} As demais informações continuam disponíveis.</span><button onClick={()=>void load(failedSources)}>Tentar novamente</button></>:loadingSources.length?<><LoaderCircle className={styles.spin} size={18}/><span>Carregando {loadingSources.map(source=>sourceLabels[source]).join(", ")}…</span></>:<><Activity size={18}/><span>Relatório atualizado.</span></>}</div>
 <nav className={styles.tabs}>{tabs.map(x=><button className={tab===x.id?styles.active:""} onClick={()=>setTab(x.id)} key={x.id}><x.Icon size={18}/>{x.label}</button>)}</nav>
 {tab==="overview"&&<><section className={styles.kpis}>{[{label:"Custo total",value:brl.format(cost),Icon:Coins,tone:"red"},{label:"Receita total",value:brl.format(revenue),Icon:BadgeDollarSign,tone:"green"},{label:"Lucro total",value:brl.format(profit),Icon:TrendingUp,tone:"blue"},{label:"Margem de lucro",value:`${margin.toFixed(2)}%`,Icon:Percent,tone:"purple"},{label:"Custo por animal",value:brl.format(total?cost/total:0),Icon:PiggyBank,tone:"orange"},{label:"Lucro por animal",value:brl.format(total?profit/total:0),Icon:Activity,tone:"darkgreen"}].map(x=><article data-tone={x.tone} key={x.label}><x.Icon/><div><span>{x.label}</span><strong>{x.value}</strong><small>Período selecionado</small></div></article>)}</section><Filters from={from} to={to} setFrom={setFrom} setTo={setTo} status={status} setStatus={setStatus} category={category} setCategory={setCategory} search={search} setSearch={setSearch} reset={reset}/><section className={styles.overviewGrid}><div className={styles.panel}><h2>Resumo por categoria</h2><div className={styles.costTable}>{costs.length?costs.map(([name,value],i)=><div key={name}><span className={styles.dot} style={{background:["#1768d4","#e62f35","#f59e0b","#16803c","#7c3aed"][i%5]}}/><strong>{name}</strong><b>{brl.format(value)}</b><i><em style={{width:`${cost?value/cost*100:0}%`}}/></i><small>{cost?`${(value/cost*100).toFixed(1)}%`:"0%"}</small></div>):<p className={styles.empty}>Nenhum custo no período.</p>}</div></div><div className={styles.panel}><h2>Distribuição dos custos</h2><div className={styles.donutWrap}><div className={styles.donut} style={{"--fill":`${Math.min(cost/(cost+revenue||1)*100,100)}%`} as React.CSSProperties}><span><strong>{brl.format(cost)}</strong><small>Custo total</small></span></div><div className={styles.legend}>{costs.slice(0,5).map(([name,value],i)=><div key={name}><i style={{background:["#1768d4","#e62f35","#f59e0b","#16803c","#7c3aed"][i]}}/><span>{name}</span><strong>{brl.format(value)}</strong></div>)}</div></div></div></section></>}
 {tab==="reproduction"&&<Reproduction data={repro} report={report} females={females} profit={profit}/>} {tab==="batches"&&<><Filters from={from} to={to} setFrom={setFrom} setTo={setTo} status={status} setStatus={setStatus} category={category} setCategory={setCategory} search={search} setSearch={setSearch} reset={reset}/><LotsTable items={filteredLots}/></>} {tab==="females"&&<><Filters from={from} to={to} setFrom={setFrom} setTo={setTo} status={status} setStatus={setStatus} category={category} setCategory={setCategory} search={search} setSearch={setSearch} reset={reset} hideCategory/><FemalesTable items={filteredFemales}/></>}
 <footer className={styles.footer}>Os dados são calculados com base nos lançamentos realizados no sistema. <span>Atualizado em {new Date().toLocaleString("pt-BR")}</span></footer></div>}

interface FiltersProps{from:string;to:string;setFrom:(value:string)=>void;setTo:(value:string)=>void;status:string;setStatus:(value:string)=>void;category:string;setCategory:(value:string)=>void;search:string;setSearch:(value:string)=>void;reset:()=>void;hideCategory?:boolean}
function Filters({from,to,setFrom,setTo,status,setStatus,category,setCategory,search,setSearch,reset,hideCategory=false}:FiltersProps){return <section className={styles.filters}><label><span>Data inicial</span><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label><span>Data final</span><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label><span>Situação</span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todas</option><option value="active">Ativos</option><option value="sold">Vendidos</option><option value="finished">Finalizados</option></select></label>{!hideCategory&&<label><span>Categoria</span><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Todas</option><option>Leitão</option><option>Terminação</option><option>Matriz</option><option>Marrã</option><option>Reprodutor</option></select></label>}<label className={styles.search}><span>Buscar</span><div><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por identificação…"/></div></label><button className={styles.filterButton}><Filter size={17}/>Aplicar filtros</button><button className={styles.clear} onClick={reset}>Limpar</button></section>}
function Reproduction({data,report,females,profit}:{data:Repro|null;report:Report|null;females:Female[];profit:number}){
 const [year,setYear]=useState(String(new Date().getFullYear())),[farm,setFarm]=useState("");
 const farms=[...new Map(females.filter(x=>x.farm_name).map(x=>[x.farm,x.farm_name!])).entries()];
 const selectedFemales=females.filter(x=>(!farm||x.farm===farm)&&x.status==="active");
 const selectedReport:Report|null=report?{...report,items:report.items.filter(x=>!farm||x.farm===farms.find(f=>f[0]===farm)?.[1])}:null;
 const cycles=selectedFemales.flatMap(f=>(f.reproductive_cycles||[]).filter(c=>(c.mating_date||c.birth_date||"").startsWith(year)).map(c=>({female:f,cycle:c})));
 const births=cycles.filter(x=>x.cycle.birth_date),confirmed=cycles.filter(x=>x.cycle.pregnancy_confirmed),matrices=selectedFemales.filter(x=>x.category==="Matriz").length;
 const born=births.reduce((s,x)=>s+(x.cycle.live_born||0),0),totalBorn=births.reduce((s,x)=>s+(x.cycle.total_born||0),0),stillborn=births.reduce((s,x)=>s+(x.cycle.stillborn||0),0),mummified=births.reduce((s,x)=>s+(x.cycle.mummified||0),0),weaned=births.reduce((s,x)=>s+(x.cycle.weaned_quantity||0),0),mortality=births.reduce((s,x)=>s+(x.cycle.mortality||0),0);
 const avg=(values:number[])=>values.length?values.reduce((s,v)=>s+v,0)/values.length:null,metric=(value:number|null,suffix="")=>value===null?"—":`${value.toLocaleString("pt-BR",{maximumFractionDigits:2})}${suffix}`;
 const pregnancyRate=cycles.length?confirmed.length/cycles.length*100:null,farrowingRate=confirmed.length?births.length/confirmed.length*100:null;
 const birthWeights=births.map(x=>x.cycle.avg_birth_weight_kg).filter((v):v is number=>v!=null),weaningWeights=births.map(x=>x.cycle.avg_weaning_weight_kg).filter((v):v is number=>v!=null),lactationDays=births.map(x=>x.cycle.lactation_days).filter((v):v is number=>v!=null);
 const birthIntervals=selectedFemales.flatMap(f=>{const dates=(f.reproductive_cycles||[]).map(c=>c.birth_date).filter((v):v is string=>!!v).sort();return dates.slice(1).map((d,i)=>(new Date(d).getTime()-new Date(dates[i]).getTime())/86400000)});
 const weanToMating=selectedFemales.flatMap(f=>{const cs=(f.reproductive_cycles||[]).filter(c=>c.mating_date).sort((a,b)=>(a.mating_date||"").localeCompare(b.mating_date||""));return cs.slice(0,-1).map((c,i)=>c.weaning_date?(new Date(cs[i+1].mating_date!).getTime()-new Date(c.weaning_date).getTime())/86400000:null).filter((v):v is number=>v!=null&&v>=0)});
 const empty=selectedFemales.filter(x=>["vazia","aguardando_cobertura"].includes(x.reproductive_status)).length,k=data?.kpis;
 const top=[
  {icon:"🐖",label:"Leitões desmamados por matriz/ano",meta:"Ciclos do ano",value:matrices?metric(weaned/matrices):"—",tone:"green",state:weaned?"Calculado":"Sem dados"},
  {icon:"📈",label:"Taxa de parto",meta:"Gestações confirmadas",value:metric(farrowingRate,"%"),tone:"orange",state:farrowingRate!==null?"Calculado":"Sem dados"},
  {icon:"🐷",label:"Peso médio ao desmame",meta:"Desmames registrados",value:metric(avg(weaningWeights)," kg"),tone:"red",state:weaningWeights.length?"Calculado":"Sem dados"},
  {icon:"⚕",label:"Mortalidade na creche",meta:"Saídas da fase",value:"—",tone:"red",state:"Sem dados"},
  {icon:"♻",label:"Conversão alimentar geral",meta:"Ração ÷ ganho de peso",value:"—",tone:"green",state:"Sem dados"},
  {icon:"◉",label:"Lucro por matriz",meta:"Resultado do período",value:matrices?brl.format(profit/matrices):"—",tone:"green",state:matrices?"Calculado":"Sem dados"},
 ];
 const groups=[
  {title:"REPRODUÇÃO",tone:"pink",rows:[["Taxa de Cobertura (%)","—",metric(matrices?cycles.length/matrices*100:null,"%")],["Taxa de Prenhez (%)","—",metric(pregnancyRate,"%")],["Taxa de Parto (%)","—",metric(farrowingRate,"%")],["Partos por Matriz/ano","—",metric(matrices?births.length/matrices:null)],["Intervalo Desmame - Cio (dias)","—",metric(avg(weanToMating))],["Intervalo entre Partos (dias)","—",metric(avg(birthIntervals))],["Dias não Produtivos (DNP)","—","—"],["Matrizes Vazias (%)","—",metric(selectedFemales.length?empty/selectedFemales.length*100:null,"%")]]},
  {title:"NASCIMENTO",tone:"purple",rows:[["Leitões Nascidos Vivos","—",num.format(born)],["Leitões Nascidos Mortos (%)","—",metric(totalBorn?stillborn/totalBorn*100:null,"%")],["Leitões Mumificados (%)","—",metric(totalBorn?mummified/totalBorn*100:null,"%")],["Total de Nascidos","—",num.format(totalBorn)],["Média de Nascidos por Parto","—",metric(births.length?totalBorn/births.length:null)],["Peso Médio ao Nascer (kg)","—",metric(avg(birthWeights))]]},
  {title:"MATERNIDADE",tone:"orange",rows:[["Leitões Desmamados","—",num.format(weaned)],["Leitões Desmamados/matriz","—",metric(births.length?weaned/births.length:null)],["Mortalidade na Maternidade (%)","—",metric(born?mortality/born*100:null,"%")],["Peso Médio ao Desmame (kg)","—",metric(avg(weaningWeights))],["Idade Média ao Desmame (dias)","—",metric(avg(lactationDays))],["Mortalidade por Esmagamento (%)","—","—"]]},
  {title:"CRECHE",tone:"blue",rows:[["Quantidade Alojada","—",phaseTotal(selectedReport,"Leitão")],["Peso de Entrada / Atual (kg)","—",phaseWeight(selectedReport,"Leitão")],["Ganho de Peso Diário (kg)","—","—"],["Conversão Alimentar","—","—"],["Consumo de Ração (kg)","—","—"],["Mortalidade (%)","—","—"]]},
  {title:"CRESCIMENTO",tone:"green",rows:[["Quantidade Alojada","—",phaseTotal(selectedReport,"Crescimento")],["Peso Médio (kg)","—",phaseWeight(selectedReport,"Crescimento")],["Ganho de Peso Diário (kg)","—","—"],["Conversão Alimentar","—","—"],["Consumo de Ração (kg)","—","—"],["Mortalidade (%)","—","—"]]},
  {title:"TERMINAÇÃO",tone:"violet",rows:[["Peso Médio (kg)","—",phaseWeight(selectedReport,"Terminação")],["Dias até o Abate","—","—"],["Conversão Alimentar","—","—"],["Ganho de Peso Diário (kg)","—","—"],["Mortalidade (%)","—","—"],["Animais Vendidos","—",soldTotal(selectedReport)]]},
 ];
 const distribution=[["Maternidade",selectedFemales.filter(x=>x.reproductive_status==="lactante").length,"#8b45c8"],["Creche",categoryTotal(selectedReport,"Leitão"),"#168ee5"],["Crescimento",categoryTotal(selectedReport,"Crescimento"),"#24bd9b"],["Terminação",categoryTotal(selectedReport,"Terminação"),"#f59e0b"],["Reprodução",selectedFemales.length+(k?.reprodutores||0),"#f23b78"]] as [string,number,string][];
 return <div className={styles.productivity}><div className={styles.productiveHeader}><div><h2>Índices Produtivos - Suinocultura</h2><p>Indicadores consolidados a partir dos lançamentos disponíveis no sistema.</p></div><HeartPulse size={27}/></div><section className={styles.productiveFilters}><label><span>Ano</span><select value={year} onChange={e=>setYear(e.target.value)}>{[0,1,2,3,4].map(n=><option key={n}>{new Date().getFullYear()-n}</option>)}</select></label><label><span>Fazenda</span><select value={farm} onChange={e=>setFarm(e.target.value)}><option value="">Todas</option>{farms.map(([id,name])=><option value={id} key={id}>{name}</option>)}</select></label><button><Filter size={16}/>Aplicar filtros</button><button className={styles.clear} onClick={()=>{setYear(String(new Date().getFullYear()));setFarm("")}}>Limpar</button></section><section className={styles.productiveKpis}>{top.map(x=><article data-tone={x.tone} key={x.label}><span className={styles.productiveIcon}>{x.icon}</span><div><small>{x.label}</small><em>{x.meta}</em><strong>{x.value}</strong><b>{x.state}</b></div></article>)}</section><section className={styles.indicatorGrid}>{groups.map(group=><article data-tone={group.tone} key={group.title}><h3><i/> {group.title}</h3><div className={styles.indicatorHead}><span>Indicador</span><span>Meta cadastrada</span><span>Resultado</span></div>{group.rows.map(row=><div className={styles.indicatorRow} key={row[0]}><strong>{row[0]}</strong><span>{row[1]}</span><b>{row[2]}</b></div>)}</article>)}</section><section className={styles.phasePanel}><h3>DISTRIBUIÇÃO DOS ANIMAIS POR FASE</h3><div><div className={styles.phaseDonut}><span><strong>{num.format(distribution.reduce((s,x)=>s+x[1],0))}</strong><small>Total</small></span></div><div className={styles.phaseLegend}>{distribution.map(([name,value,color])=><div key={name}><i style={{background:color}}/><span>{name}</span><b>{num.format(value)}</b></div>)}</div></div></section></div>
}
const isLivestockTransaction=(transaction:Transaction)=>/su[ií]n|animal|rebanho|ra[cç][aã]o|matriz|leit[aã]o|marr[aã]|reprodutor/i.test(`${transaction.category_name} ${transaction.description} ${transaction.reference||""}`);
const categoryTotal=(report:Report|null,category:string)=>(report?.items||[]).filter(x=>x.category===category&&x.status==="active").reduce((s,x)=>s+x.quantity,0);
const phaseTotal=(report:Report|null,category:string)=>num.format(categoryTotal(report,category));
const phaseWeight=(report:Report|null,category:string)=>{const rows=(report?.items||[]).filter(x=>x.category===category&&x.avg_weight);return rows.length?`${(rows.reduce((s,x)=>s+(x.avg_weight||0),0)/rows.length).toFixed(1)} kg`:"—"};
const soldTotal=(report:Report|null)=>num.format((report?.items||[]).filter(x=>x.status==="sold").reduce((s,x)=>s+x.quantity,0));
function LotsTable({items}:{items:Item[]}){return <section className={styles.tablePanel}><div className={styles.tableTitle}><div><span>LOTES</span><h2>Relatório Geral dos Lotes</h2></div><strong>{items.length} registros</strong></div><div className={styles.tableScroll}><table><thead><tr><th>Lote</th><th>Categoria</th><th>Quantidade</th><th>Peso médio</th><th>Fazenda</th><th>Entrada</th><th>Status</th></tr></thead><tbody>{items.length?items.map(x=><tr key={x.id}><td><b>{x.batch_code}</b><small>{x.name||"Sem nome"}</small></td><td>{x.category||"-"}</td><td>{num.format(x.quantity)}</td><td>{x.avg_weight?`${num.format(x.avg_weight)} kg`:"-"}</td><td>{x.farm}</td><td>{x.entry_date?new Date(x.entry_date+"T00:00:00").toLocaleDateString("pt-BR"):"-"}</td><td><span className={styles.status} data-status={x.status}>{x.status}</span></td></tr>):<tr><td colSpan={7} className={styles.empty}>Nenhum lote encontrado.</td></tr>}</tbody></table></div></section>}
function FemalesTable({items}:{items:Female[]}){
 const active=items.filter(x=>x.status==="active").length,empty=items.filter(x=>x.reproductive_status==="vazia").length,discarded=items.filter(x=>x.status!=="active").length,pregnant=items.filter(x=>x.reproductive_status==="gestante").length,lactating=items.filter(x=>x.reproductive_status==="lactante").length;
 const cards=[{label:"Total de Matrizes",value:items.length,meta:"Todas as categorias",tone:"purple",icon:"🐖"},{label:"Matrizes Ativas",value:active,meta:percentage(active,items.length),tone:"green",icon:"✓"},{label:"Vazias",value:empty,meta:percentage(empty,items.length),tone:"orange",icon:"✓"},{label:"Descartadas",value:discarded,meta:percentage(discarded,items.length),tone:"red",icon:"×"},{label:"Gestantes",value:pregnant,meta:percentage(pregnant,items.length),tone:"blue",icon:"♀"},{label:"Lactantes",value:lactating,meta:percentage(lactating,items.length),tone:"pink",icon:"◔"}];
 return <div className={styles.femaleReport}><div className={styles.femaleHeading}><div><h2>Relatório das Matrizes</h2><p>Acompanhe o desempenho reprodutivo e produtivo de todas as matrizes.</p></div><UsersRound size={28}/></div><section className={styles.femaleKpis}>{cards.map(x=><article data-tone={x.tone} key={x.label}><span>{x.icon}</span><div><small>{x.label}</small><strong>{num.format(x.value)}</strong><em>{x.meta}</em></div></article>)}</section><section className={styles.tablePanel}><div className={styles.tableTitle}><div><span>LISTA DE MATRIZES</span><h2>Matrizes cadastradas</h2></div><strong>{items.length} animais</strong></div><div className={styles.tableScroll}><table className={styles.femaleTable}><thead><tr><th>Matriz</th><th>Categoria</th><th>Situação</th><th>Fase atual</th><th>Últ. cobertura</th><th>Partos</th><th>Nascidos vivos<small>Média/parto</small></th><th>Desmamados<small>Média/parto</small></th><th>Parto provável</th><th>Ações</th></tr></thead><tbody>{items.length?items.map(x=>{const cycles=x.reproductive_cycles||[],last=cycles.at(-1),finished=cycles.filter(c=>c.birth_date),live=finished.reduce((s,c)=>s+(c.live_born||0),0),weaned=finished.reduce((s,c)=>s+(c.weaned_quantity||0),0);return <tr key={x.id}><td><b>{x.identifier}</b></td><td>{x.category}</td><td><span className={styles.matrixSituation} data-status={x.status}>{x.status==="active"?"Ativa":"Descartada"}</span></td><td>{phaseName(x.reproductive_status)}</td><td>{formatDate(last?.mating_date)}</td><td>{x.birth_count||finished.length}</td><td>{finished.length?(live/finished.length).toFixed(1):"—"}</td><td>{finished.length?(weaned/finished.length).toFixed(1):"—"}</td><td>{formatDate(last?.expected_birth_date)}</td><td><div className={styles.rowActions}><button title="Visualizar matriz">◉</button><button title="Ver indicadores">▥</button></div></td></tr>}):<tr><td colSpan={10} className={styles.empty}>Nenhuma matriz encontrada.</td></tr>}</tbody></table></div><div className={styles.tableFooter}><span>Mostrando {items.length} matrizes</span><div><button disabled>Anterior</button><b>1</b><button disabled>Próximo</button></div></div></section></div>
}
const percentage=(value:number,total:number)=>total?`${(value/total*100).toFixed(2)}% do total`:"0% do total";
const formatDate=(value?:string)=>value?new Date(value+"T00:00:00").toLocaleDateString("pt-BR"):"—";
const phaseName=(value:string)=>({gestante:"Gestação",lactante:"Lactação",vazia:"Vazia",coberta:"Coberta",aguardando_cobertura:"Aguardando cobertura",descanso:"Descanso"} as Record<string,string>)[value]||value||"—";
