# Generated by Django 5.2.13 on 2026-05-01 01:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organizationaddress_organizationcontact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('stock_general', 'Geral de Estoque'), ('stock_movement', 'Movimentação de Estoque'), ('stock_minimum', 'Estoque Mínimo'), ('stock_validity', 'Validade de Estoque'), ('finance_cashflow', 'Fluxo de Caixa'), ('finance_dre', 'Demonstração de Resultados'), ('finance_category', 'Por Categoria'), ('finance_comparative', 'Comparativo Financeiro'), ('livestock_inventory', 'Inventário de Rebanho'), ('livestock_movement', 'Movimentação de Animais'), ('livestock_mortality', 'Mortalidade'), ('livestock_weight', 'Peso Médio'), ('crops_area', 'Área Plantada'), ('crops_harvest', 'Safra/Produção'), ('farm_summary', 'Resumo por Fazenda'), ('farm_kpi', 'Indicadores KPI'), ('dashboard', 'Dashboard Executivo')], max_length=30)),
                ('default_filters', models.JSONField(blank=True, default=dict)),
                ('default_date_range', models.JSONField(blank=True, default=dict)),
                ('default_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10)),
                ('include_charts', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
                ('allowed_roles', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_configs', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Report Configuration',
                'verbose_name_plural': 'Report Configurations',
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('organization', 'report_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('frequency', models.CharField(choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('yearly', 'Anual')], max_length=20)),
                ('schedule_time', models.TimeField()),
                ('schedule_day', models.PositiveIntegerField(blank=True, help_text='Dia do mês para agendamento mensal (1-28)', null=True)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('send_email', models.BooleanField(default=False)),
                ('email_recipients', models.JSONField(blank=True, default=list)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to='organizations.organization')),
                ('report_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reports.reportconfig')),
            ],
            options={
                'verbose_name': 'Report Schedule',
                'verbose_name_plural': 'Report Schedules',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportWidget',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('widget_type', models.CharField(max_length=50)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('position_x', models.PositiveIntegerField(default=0)),
                ('position_y', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=4)),
                ('height', models.PositiveIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_widgets', to='organizations.organization')),
            ],
            options={
                'ordering': ['position_y', 'position_x'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('stock_general', 'Geral de Estoque'), ('stock_movement', 'Movimentação de Estoque'), ('stock_minimum', 'Estoque Mínimo'), ('stock_validity', 'Validade de Estoque'), ('finance_cashflow', 'Fluxo de Caixa'), ('finance_dre', 'Demonstração de Resultados'), ('finance_category', 'Por Categoria'), ('finance_comparative', 'Comparativo Financeiro'), ('livestock_inventory', 'Inventário de Rebanho'), ('livestock_movement', 'Movimentação de Animais'), ('livestock_mortality', 'Mortalidade'), ('livestock_weight', 'Peso Médio'), ('crops_area', 'Área Plantada'), ('crops_harvest', 'Safra/Produção'), ('farm_summary', 'Resumo por Fazenda'), ('farm_kpi', 'Indicadores KPI'), ('dashboard', 'Dashboard Executivo')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('date_range', models.JSONField(blank=True, default=dict)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/generated/')),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('format_used', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], max_length=10)),
                ('preview_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='organizations.organization')),
                ('report_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='reports.reportconfig')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='reports.reportschedule')),
            ],
            options={
                'verbose_name': 'Generated Report',
                'verbose_name_plural': 'Generated Reports',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['organization', 'status'], name='reports_gen_organiz_1d1c28_idx'), models.Index(fields=['created_at'], name='reports_gen_created_6243b5_idx')],
            },
        ),
    ]
