import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BadgePercent, CheckCircle2, Headphones, RefreshCcw, ShieldCheck } from "lucide-react";
import { MarketingPage } from "@/components/marketing/MarketingPage";
import { PublicPlans } from "@/components/marketing/PublicPlans";

export const metadata: Metadata = { title:"Planos e preços | AgroManage", description:"Compare planos, preços e limites comerciais do AgroManage." };
const assurances=[[RefreshCcw,"Evolua quando precisar","Altere o plano conforme sua operação cresce."],[Headphones,"Implantação acompanhada","Conte com orientação para organizar o início do uso."],[ShieldCheck,"Ambiente protegido","Dados e acessos separados por organização."],[BadgePercent,"Condições comerciais","Descontos podem ser aplicados à assinatura pela equipe responsável."]] as const;
export default function PlanosPage(){return <MarketingPage eyebrow="Planos e preços" title="Invista no controle da sua operação" description="Compare ciclos, preços e limites atualizados diretamente pela equipe AgroManage."><section className="marketing-section pricing-section"><div className="marketing-container"><PublicPlans showBillingToggle/><p className="pricing-note">Valores exibidos em reais. Condições personalizadas podem ser definidas conforme o porte e as necessidades da operação.</p></div></section><section className="plan-assurance"><div className="marketing-container assurance-grid">{assurances.map(([Icon,title,text])=><article key={title}><Icon size={23}/><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section><section className="marketing-section"><div className="marketing-container plan-guide"><div><div className="eyebrow">Como escolher</div><h2>O plano certo considera mais do que o tamanho da fazenda</h2><p>Nossa equipe avalia número de usuários, unidades produtivas, módulos necessários e volume de operação para orientar a melhor configuração.</p><Link href="/contato" className="marketing-button primary">Conversar com um especialista <ArrowRight size={17}/></Link></div><ul><li><CheckCircle2/> Quantidade de usuários e responsabilidades</li><li><CheckCircle2/> Número de fazendas ou unidades</li><li><CheckCircle2/> Produção agrícola, pecuária ou operação mista</li><li><CheckCircle2/> Necessidade de relatórios e armazenamento</li><li><CheckCircle2/> Ciclo de cobrança mensal, anual ou personalizado</li></ul></div></section></MarketingPage>}
