# Generated by Django 5.2.13 on 2026-05-01 00:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(default='Principal', help_text='Ex: Sede, Filial, Depósito', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('street', models.CharField(max_length=255)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('complement', models.CharField(blank=True, max_length=255)),
                ('neighborhood', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('is_main', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Endereço da Organização',
                'verbose_name_plural': 'Endereços da Organização',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Nome do responsável ou setor', max_length=150)),
                ('contact_type', models.CharField(choices=[('phone', 'Telefone'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('other', 'Outro')], default='phone', max_length=20)),
                ('value', models.CharField(help_text='Número ou email', max_length=255)),
                ('is_main', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Contato da Organização',
                'verbose_name_plural': 'Contatos da Organização',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
