"use client";

import {FormEvent,useEffect,useMemo,useRef,useState} from "react";
import {AlertTriangle,Bot,Check,ChevronRight,Copy,Leaf,LoaderCircle,Menu,MessageSquarePlus,Mic,MoreHorizontal,PawPrint,Pencil,Send,Square,Sparkles,Sprout,ThumbsDown,ThumbsUp,Trash2,Volume2,Wheat,X} from "lucide-react";
import {aiAssistantService,aiAssistantError,type Subject,type Message,type Conversation,type Quota} from "@/services/aiAssistantService";
import { MarkdownMessage } from "@/components/ui/MarkdownMessage";
import { useBrowserVoice } from "@/hooks/useBrowserVoice";
import styles from "./page.module.css";

const subjects=[{value:"general",label:"Geral",Icon:Sparkles},{value:"crops",label:"Plantações",Icon:Wheat},{value:"livestock",label:"Animais",Icon:PawPrint},{value:"feeding",label:"Alimentação",Icon:Leaf},{value:"management",label:"Gestão rural",Icon:Sprout}] as const;
const suggestions=[
 {subject:"crops" as Subject,Icon:Wheat,title:"Folhas amareladas",text:"Minha plantação está com folhas amareladas. O que devo observar?"},
 {subject:"livestock" as Subject,Icon:PawPrint,title:"Comportamento animal",text:"Quais sinais indicam estresse térmico nos animais?"},
 {subject:"feeding" as Subject,Icon:Leaf,title:"Consumo de ração",text:"Como avaliar o consumo de ração de um lote?"},
 {subject:"management" as Subject,Icon:Sprout,title:"Planejar o ciclo",text:"Quais dados preciso para planejar o próximo ciclo produtivo?"},
];
const label=(value:Subject)=>subjects.find(item=>item.value===value)?.label||"Geral";
function Mark({small=false}:{small?:boolean}){return <span className={`${styles.brandMark} ${small?styles.brandMarkSmall:""}`}><Leaf size={small?18:27}/><Sparkles className={styles.brandSpark} size={small?9:12}/></span>}

export default function Page(){
 const [conversations,setConversations]=useState<Conversation[]>([]),[selected,setSelected]=useState<Conversation|null>(null),[messages,setMessages]=useState<Message[]>([]),[quota,setQuota]=useState<Quota|null>(null),[subject,setSubject]=useState<Subject>("general"),[question,setQuestion]=useState(""),[sending,setSending]=useState(false),[loading,setLoading]=useState(true),[historyOpen,setHistoryOpen]=useState(false),[menuOpen,setMenuOpen]=useState<string|null>(null),[copied,setCopied]=useState<string|null>(null),[firstName,setFirstName]=useState("Produtor"),[error,setError]=useState("");
 const voice=useBrowserVoice();
 const [today]=useState(()=>Date.now());
 const messagesRef=useRef<HTMLElement>(null),textareaRef=useRef<HTMLTextAreaElement>(null);
 useEffect(()=>{let active=true;queueMicrotask(async()=>{if(!active)return;try{const u=JSON.parse(localStorage.getItem("user")||"{}");setFirstName(u.full_name?.split(" ")[0]||"Produtor")}catch{}try{const [history,usage]=await Promise.all([aiAssistantService.conversations(),aiAssistantService.quota()]);if(active){setConversations(history);setQuota(usage)}}catch(error){if(active)setError(aiAssistantError(error))}finally{if(active)setLoading(false)}});return()=>{active=false}},[]);
 useEffect(()=>{const container=messagesRef.current;if(!container)return;const frame=window.requestAnimationFrame(()=>container.scrollTo({top:container.scrollHeight,behavior:"smooth"}));return()=>window.cancelAnimationFrame(frame)},[selected?.id,messages.length,sending]);
 const grouped=useMemo(()=>conversations.reduce<Record<string,Conversation[]>>((acc,item)=>{const days=Math.floor((today-new Date(item.updated_at).getTime())/864e5),group=days<1?"Hoje":days<7?"Últimos 7 dias":"Anteriores";(acc[group]??=[]).push(item);return acc},{}),[conversations,today]);
 const newChat=()=>{if(sending)return;setSelected(null);setMessages([]);setQuestion("");setSubject("general");setHistoryOpen(false);setError("")};
 const dictate=()=>{if(voice.listening){voice.stopDictation();return}const base=question;voice.dictate(text=>setQuestion(`${base}${base&&text?" ":""}${text}`))};
 const open=async(item:Conversation)=>{if(sending)return;setHistoryOpen(false);setMenuOpen(null);setError("");try{const data=await aiAssistantService.conversation(item.id);setSelected(data);setMessages((data.messages||[]).filter(message=>message.status!=="blocked"));setSubject(data.subject)}catch(error){setError(aiAssistantError(error))}};
 const remove=async(item:Conversation)=>{if(sending)return;try{await aiAssistantService.remove(item.id);setConversations(v=>v.filter(x=>x.id!==item.id));if(selected?.id===item.id)newChat()}catch(error){setError(aiAssistantError(error))}};
 const rename=async(item:Conversation)=>{if(sending)return;const title=window.prompt("Novo nome da conversa",item.title)?.trim();if(!title)return;try{const data=await aiAssistantService.rename(item.id,title);setConversations(v=>v.map(x=>x.id===item.id?data:x));setSelected(v=>v?.id===item.id?{...v,title:data.title}:v);setMenuOpen(null)}catch(error){setError(aiAssistantError(error))}};
 const send=async(event?:FormEvent)=>{
  event?.preventDefault();const clean=question.trim();if(sending||!clean)return;
  if(clean.length<3||clean.length>4000){setError("Escreva uma pergunta entre 3 e 4.000 caracteres.");return}
  if(!quota?.enabled){setError("O Assistente IA não está disponível neste plano ou não foi possível consultar sua franquia.");return}
  if(quota.remaining===0){setError("A franquia mensal de perguntas foi atingida.");return}
  setSending(true);setError("");let conversation=selected;
  try{
   if(!conversation){conversation=await aiAssistantService.create(subject);setSelected(conversation);setConversations(v=>[conversation!,...v])}
   const result=await aiAssistantService.ask(conversation.id,clean);setQuota(result.quota);setQuestion("");
   setMessages(v=>[...v,{id:`local-${Date.now()}`,role:"user",content:clean,status:"completed",latency_ms:null,created_at:new Date().toISOString()},result.message]);
   try{const data=await aiAssistantService.conversation(conversation.id);setSelected(data);setMessages((data.messages||[]).filter(message=>message.status!=="blocked"));setConversations(v=>[data,...v.filter(x=>x.id!==data.id)])}catch{setError("A resposta foi recebida, mas não foi possível atualizar o histórico.")}

  }catch(error){
   setError(aiAssistantError(error));
   if(conversation){try{const data=await aiAssistantService.conversation(conversation.id);setSelected(data);setMessages((data.messages||[]).filter(message=>message.status!=="blocked"))}catch{}}
   try{setQuota(await aiAssistantService.quota())}catch{}
  }finally{setSending(false)}
 };
 const quotaPercent=quota?.limit?Math.min(quota.used/quota.limit*100,100):0;
 const lastAssistantMessage=[...messages].reverse().find(message=>message.role==="assistant");
 if(loading)return <div className={styles.loading}><LoaderCircle className={styles.spin}/><span>Preparando o Agro Assistente…</span></div>;
 return <div className={styles.shell} onClick={()=>menuOpen&&setMenuOpen(null)}>
  <aside className={`${styles.history} ${historyOpen?styles.historyOpen:""}`}><div className={styles.historyHeader}><div><Mark small/><div><strong>Agro Assistente</strong><small>Seu consultor rural digital</small></div></div><button className={styles.mobileClose} onClick={()=>setHistoryOpen(false)}><X/></button></div><button className={styles.newButton} onClick={newChat}><MessageSquarePlus size={18}/>Nova conversa</button><div className={styles.historyList}>{conversations.length===0?<div className={styles.emptyHistory}><Bot/><strong>Nenhuma conversa ainda</strong><span>Suas dúvidas ficarão organizadas aqui.</span></div>:Object.entries(grouped).map(([group,items])=><section className={styles.historyGroup} key={group}><h2>{group}</h2>{items.map(item=><div data-subject={item.subject} className={`${styles.historyItem} ${selected?.id===item.id?styles.active:""}`} key={item.id}><button onClick={()=>open(item)}><span>{item.title}</span><small>{label(item.subject)} · {new Date(item.updated_at).toLocaleDateString("pt-BR")}</small></button><div className={styles.itemActions}><button onClick={e=>{e.stopPropagation();setMenuOpen(menuOpen===item.id?null:item.id)}}><MoreHorizontal size={17}/></button>{menuOpen===item.id&&<div className={styles.actionMenu} onClick={e=>e.stopPropagation()}><button onClick={()=>rename(item)}><Pencil size={14}/>Renomear</button><button className={styles.dangerAction} onClick={()=>remove(item)}><Trash2 size={14}/>Excluir</button></div>}</div></div>)}</section>)}</div><div className={styles.quotaCard}><div><span>Franquia mensal</span><strong>{quota ? `${quota.used} de ${quota.limit ?? "ilimitadas"}` : "Indisponível"}</strong></div><div className={styles.quotaBar}><i style={{width:`${quotaPercent}%`}}/></div><small>{quota ? (quota.remaining===null ? "Perguntas ilimitadas" : `${quota.remaining} perguntas disponíveis`) : "Não foi possível consultar a franquia"}</small></div></aside>
  {historyOpen&&<button className={styles.overlay} onClick={()=>setHistoryOpen(false)}/>}<main className={styles.chat}><header className={styles.chatHeader}><div><button className={styles.historyToggle} onClick={()=>setHistoryOpen(true)}><Menu/></button><Mark/><div><h1>{selected?.title||"Agro Assistente"}</h1><p><i/>Orientações para sua atividade rural</p></div></div><div className={styles.headerBadges}>{lastAssistantMessage&&voice.canSpeak&&<button className={styles.listenButton} onClick={()=>voice.speaking?voice.stopSpeaking():voice.speak(lastAssistantMessage.content)}>{voice.speaking?<Square/>:<Volume2/>}{voice.speaking?"Parar":"Ouvir resposta"}</button>}<span className={styles.subjectBadge} data-subject={subject}>{label(subject)}</span></div></header>
  <section className={styles.messages} ref={messagesRef}>{messages.length===0?<div className={styles.welcome}><Mark/><small>AGRO ASSISTENTE</small><h2>Olá, {firstName}. Como posso ajudar?</h2><p>Escolha um assunto ou descreva sua situação. Organize dúvidas sobre plantações, animais, alimentação e gestão rural.</p><div className={styles.contextCards}>{subjects.slice(1).map(item=><span key={item.value} data-subject={item.value}><item.Icon size={15}/>{item.label}</span>)}</div><div className={styles.suggestions}>{suggestions.map(item=><button data-subject={item.subject} key={item.title} onClick={()=>{setSubject(item.subject);setQuestion(item.text);textareaRef.current?.focus()}}><span><item.Icon/></span><div><strong>{item.title}</strong><small>{item.text}</small></div><ChevronRight/></button>)}</div><div className={styles.disclaimer}><AlertTriangle/><span>Orientações educativas não substituem agrônomos, médicos-veterinários ou responsáveis técnicos.</span></div></div>:messages.map(message=><article className={`${styles.message} ${styles[message.role]}`} key={message.id}><span className={styles.messageAvatar}>{message.role==="assistant"?<Mark small/>:<span>Você</span>}</span><div className={styles.bubble}><div className={styles.messageLabel}>{message.role==="assistant"?"Agro Assistente":"Você"}</div>{message.role==="assistant"?<MarkdownMessage className={styles.formatted} text={message.content}/>:<div className={styles.content}>{message.content}</div>}{message.role==="assistant"&&<footer><button onClick={async()=>{try{await navigator.clipboard.writeText(message.content);setCopied(message.id);setTimeout(()=>setCopied(null),1500)}catch{setError("Não foi possível copiar a resposta.")}}}>{copied===message.id?<Check/>:<Copy/>}{copied===message.id?"Copiado":"Copiar"}</button><button><ThumbsUp/></button><button><ThumbsDown/></button><small>{message.latency_ms!==null?`${(message.latency_ms/1000).toFixed(1)}s`:""}</small></footer>}</div></article>)}{sending&&<article className={`${styles.message} ${styles.assistant}`}><span className={styles.messageAvatar}><Mark small/></span><div className={`${styles.bubble} ${styles.thinking}`}><i/><i/><i/><span>Organizando uma orientação…</span></div></article>}</section>
  <footer className={styles.composerArea}>{(error||voice.error)&&<div className={styles.error}><AlertTriangle/><span>{error||voice.error}</span><button onClick={()=>setError("")}><X/></button></div>}{quota&&!quota.enabled&&<div className={styles.planBlocked}>O Assistente IA não está disponível neste plano.</div>}<div className={styles.quickPrompts}>{["O que devo observar?","Monte um checklist","Explique de forma simples"].map(x=><button key={x} onClick={()=>setQuestion(v=>v?v+"\n"+x:x)}>{x}</button>)}</div><div className={styles.subjects}>{subjects.map(item=><button data-subject={item.value} className={subject===item.value?styles.selectedSubject:""} disabled={sending||!!selected} onClick={()=>setSubject(item.value)} key={item.value}><item.Icon/>{item.label}</button>)}</div><form className={styles.composer} onSubmit={send}><textarea ref={textareaRef} maxLength={4000} disabled={sending} value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Conte o que está acontecendo na sua fazenda…"/><div><small>{voice.listening?"Ouvindo… clique no microfone para parar.":`${question.length}/4000 · Enter envia · Shift + Enter quebra a linha`}</small><span className={styles.composerActions}>{voice.canDictate&&<button className={`${styles.voiceButton} ${voice.listening?styles.listening:""}`} type="button" aria-label={voice.listening?"Parar ditado":"Ditar mensagem"} onClick={dictate}>{voice.listening?<Square/>:<Mic/>}</button>}{question&&<button className={styles.clearButton} type="button" onClick={()=>setQuestion("")}><X/></button>}<button className={styles.sendButton} disabled={question.trim().length<3||sending||!quota?.enabled||quota.remaining===0}><Send/></button></span></div></form></footer></main>
 </div>
}
