"use client";

import {FormEvent,ReactNode,useEffect,useMemo,useRef,useState} from "react";
import {AlertTriangle,Bot,Check,ChevronRight,Copy,Leaf,LoaderCircle,Menu,MessageSquarePlus,MoreHorizontal,PawPrint,Pencil,Send,Sparkles,Sprout,ThumbsDown,ThumbsUp,Trash2,Wheat,X} from "lucide-react";
import apiClient from "@/services/api";
import styles from "./page.module.css";

type Subject="general"|"crops"|"livestock"|"feeding"|"management";
interface Message{id:string;role:"user"|"assistant";content:string;latency_ms:number|null;created_at:string}
interface Conversation{id:string;title:string;subject:Subject;updated_at:string;messages?:Message[]}
interface Quota{used:number;limit:number|null;remaining:number|null;renews_at:string}
const subjects=[{value:"general",label:"Geral",Icon:Sparkles},{value:"crops",label:"Plantações",Icon:Wheat},{value:"livestock",label:"Animais",Icon:PawPrint},{value:"feeding",label:"Alimentação",Icon:Leaf},{value:"management",label:"Gestão rural",Icon:Sprout}] as const;
const suggestions=[
 {subject:"crops" as Subject,Icon:Wheat,title:"Folhas amareladas",text:"Minha plantação está com folhas amareladas. O que devo observar?"},
 {subject:"livestock" as Subject,Icon:PawPrint,title:"Comportamento animal",text:"Quais sinais indicam estresse térmico nos animais?"},
 {subject:"feeding" as Subject,Icon:Leaf,title:"Consumo de ração",text:"Como avaliar o consumo de ração de um lote?"},
 {subject:"management" as Subject,Icon:Sprout,title:"Planejar o ciclo",text:"Quais dados preciso para planejar o próximo ciclo produtivo?"},
];
const answers:Record<Subject,string>={
 crops:"## Primeira avaliação no campo\n\nPara investigar com segurança, observe:\n\n- **Distribuição:** sintomas em toda a área ou em reboleiras.\n- **Folhas afetadas:** novas, antigas ou todas.\n- **Umidade do solo:** excesso ou falta de água.\n- **Pragas e doenças:** manchas, perfurações e insetos.\n\n### Próximo passo\nRegistre fotos, cultura, idade e histórico recente de adubação.\n\n> Evite aplicar produtos antes de confirmar a causa com um agrônomo.",
 livestock:"## Sinais importantes\n\nObserve **ofegação**, busca excessiva por água, redução do consumo e aglomeração na sombra.\n\n1. Confira água limpa e disponível.\n2. Avalie ventilação e sombra.\n3. Registre horário e temperatura.\n4. Procure assistência veterinária em casos intensos.",
 feeding:"## Checklist do consumo\n\n- Compare com a **fase produtiva**.\n- Confira quantidade e peso dos animais.\n- Observe desperdício nos comedouros.\n- Verifique validade e armazenamento da ração.\n- Relacione alterações com clima, manejo e saúde.",
 management:"## Dados para o próximo ciclo\n\n1. **Resultado anterior:** produtividade, receita e perdas.\n2. **Custos:** insumos, mão de obra e energia.\n3. **Recursos:** área, estoque, equipe e equipamentos.\n4. **Calendário:** preparo, manejo e colheita.\n\nEsses dados ajudam a comparar cenários e criar metas realistas.",
 general:"## Vamos organizar sua dúvida\n\nInforme a atividade envolvida, quando o problema começou, área ou quantidade de animais afetados e manejos recentes.\n\nQuanto mais contexto você trouxer, melhor será o direcionamento.",
};
const label=(value:Subject)=>subjects.find(item=>item.value===value)?.label||"Geral";
const inline=(text:string)=>text.split(/(\*\*[^*]+\*\*)/g).filter(Boolean).map((part,i)=>part.startsWith("**")?<strong key={i}>{part.slice(2,-2)}</strong>:part);
function Formatted({text}:{text:string}){const nodes:ReactNode[]=[];let list:string[]=[];let ordered=false;const flush=()=>{if(!list.length)return;const Tag=ordered?"ol":"ul";nodes.push(<Tag key={nodes.length}>{list.map((x,i)=><li key={i}>{inline(x)}</li>)}</Tag>);list=[]};text.split("\n").forEach((raw,i)=>{const line=raw.trim(),bullet=line.match(/^[-*]\s+(.+)/),number=line.match(/^\d+[.)]\s+(.+)/);if(bullet||number){if(list.length&&ordered!==!!number)flush();ordered=!!number;list.push((bullet?.[1]||number?.[1])!);return}flush();if(!line)return;if(line.startsWith("### "))nodes.push(<h4 key={i}>{inline(line.slice(4))}</h4>);else if(line.startsWith("## "))nodes.push(<h3 key={i}>{inline(line.slice(3))}</h3>);else if(line.startsWith("> "))nodes.push(<blockquote key={i}>{inline(line.slice(2))}</blockquote>);else nodes.push(<p key={i}>{inline(line)}</p>)});flush();return <div className={styles.formatted}>{nodes}</div>}
function Mark({small=false}:{small?:boolean}){return <span className={`${styles.brandMark} ${small?styles.brandMarkSmall:""}`}><Leaf size={small?18:27}/><Sparkles className={styles.brandSpark} size={small?9:12}/></span>}

export default function Page(){
 const [conversations,setConversations]=useState<Conversation[]>([]),[selected,setSelected]=useState<Conversation|null>(null),[messages,setMessages]=useState<Message[]>([]),[quota,setQuota]=useState<Quota|null>(null),[subject,setSubject]=useState<Subject>("general"),[question,setQuestion]=useState(""),[sending,setSending]=useState(false),[loading,setLoading]=useState(true),[historyOpen,setHistoryOpen]=useState(false),[menuOpen,setMenuOpen]=useState<string|null>(null),[copied,setCopied]=useState<string|null>(null),[firstName,setFirstName]=useState("Produtor"),[error,setError]=useState("");
 const endRef=useRef<HTMLDivElement>(null),textareaRef=useRef<HTMLTextAreaElement>(null);
 useEffect(()=>{try{const u=JSON.parse(localStorage.getItem("user")||"{}");setFirstName(u.full_name?.split(" ")[0]||"Produtor")}catch{}Promise.all([apiClient.get("/ai/conversations/"),apiClient.get("/ai/usage/")]).then(([a,b])=>{setConversations(a.data.results);setQuota(b.data)}).catch(()=>setQuota({used:0,limit:5,remaining:5,renews_at:new Date(Date.now()+2592e6).toISOString().slice(0,10)})).finally(()=>setLoading(false))},[]);
 useEffect(()=>endRef.current?.scrollIntoView({behavior:"smooth"}),[messages,sending]);
 const grouped=useMemo(()=>conversations.reduce<Record<string,Conversation[]>>((acc,item)=>{const days=Math.floor((Date.now()-new Date(item.updated_at).getTime())/864e5),group=days<1?"Hoje":days<7?"Últimos 7 dias":"Anteriores";(acc[group]??=[]).push(item);return acc},{}),[conversations]);
 const newChat=()=>{setSelected(null);setMessages([]);setQuestion("");setSubject("general");setHistoryOpen(false);setError("")};
 const open=async(item:Conversation)=>{setHistoryOpen(false);setMenuOpen(null);if(item.messages){setSelected(item);setMessages(item.messages);setSubject(item.subject);return}try{const {data}=await apiClient.get(`/ai/conversations/${item.id}/`);setSelected(data);setMessages(data.messages||[]);setSubject(data.subject)}catch{setError("Não foi possível abrir esta conversa.")}};
 const remove=async(item:Conversation)=>{if(!item.id.startsWith("demo-"))try{await apiClient.delete(`/ai/conversations/${item.id}/`)}catch{}setConversations(v=>v.filter(x=>x.id!==item.id));if(selected?.id===item.id)newChat()};
 const rename=async(item:Conversation)=>{const title=window.prompt("Novo nome da conversa",item.title)?.trim();if(!title)return;setConversations(v=>v.map(x=>x.id===item.id?{...x,title}:x));setSelected(v=>v?.id===item.id?{...v,title}:v);setMenuOpen(null);if(!item.id.startsWith("demo-"))try{await apiClient.patch(`/ai/conversations/${item.id}/`,{title})}catch{}};
 const send=async(event?:FormEvent)=>{event?.preventDefault();const clean=question.trim();if(!clean||sending)return;setQuestion("");setSending(true);const now=new Date().toISOString(),user:Message={id:`demo-user-${Date.now()}`,role:"user",content:clean,latency_ms:null,created_at:now};setMessages(v=>[...v,user]);await new Promise(r=>setTimeout(r,800));const ai:Message={id:`demo-ai-${Date.now()}`,role:"assistant",content:answers[subject],latency_ms:800,created_at:now};setMessages(v=>[...v,ai]);if(!selected){const chat={id:`demo-${Date.now()}`,title:clean.length>48?clean.slice(0,48)+"…":clean,subject,updated_at:now,messages:[user,ai]};setSelected(chat);setConversations(v=>[chat,...v])}setSending(false)};
 const quotaPercent=quota?.limit?Math.min(quota.used/quota.limit*100,100):0;
 if(loading)return <div className={styles.loading}><LoaderCircle className={styles.spin}/><span>Preparando o Agro Assistente…</span></div>;
 return <div className={styles.shell} onClick={()=>menuOpen&&setMenuOpen(null)}>
  <aside className={`${styles.history} ${historyOpen?styles.historyOpen:""}`}><div className={styles.historyHeader}><div><Mark small/><div><strong>Agro Assistente</strong><small>Seu consultor rural digital</small></div></div><button className={styles.mobileClose} onClick={()=>setHistoryOpen(false)}><X/></button></div><button className={styles.newButton} onClick={newChat}><MessageSquarePlus size={18}/>Nova conversa</button><div className={styles.historyList}>{conversations.length===0?<div className={styles.emptyHistory}><Bot/><strong>Nenhuma conversa ainda</strong><span>Suas dúvidas ficarão organizadas aqui.</span></div>:Object.entries(grouped).map(([group,items])=><section className={styles.historyGroup} key={group}><h2>{group}</h2>{items.map(item=><div data-subject={item.subject} className={`${styles.historyItem} ${selected?.id===item.id?styles.active:""}`} key={item.id}><button onClick={()=>open(item)}><span>{item.title}</span><small>{label(item.subject)} · {new Date(item.updated_at).toLocaleDateString("pt-BR")}</small></button><div className={styles.itemActions}><button onClick={e=>{e.stopPropagation();setMenuOpen(menuOpen===item.id?null:item.id)}}><MoreHorizontal size={17}/></button>{menuOpen===item.id&&<div className={styles.actionMenu} onClick={e=>e.stopPropagation()}><button onClick={()=>rename(item)}><Pencil size={14}/>Renomear</button><button className={styles.dangerAction} onClick={()=>remove(item)}><Trash2 size={14}/>Excluir</button></div>}</div></div>)}</section>)}</div><div className={styles.quotaCard}><div><span>Franquia mensal</span><strong>{quota?.used||0} de {quota?.limit||5}</strong></div><div className={styles.quotaBar}><i style={{width:`${quotaPercent}%`}}/></div><small>{quota?.remaining??5} perguntas disponíveis · modo demonstrativo não consome franquia</small></div></aside>
  {historyOpen&&<button className={styles.overlay} onClick={()=>setHistoryOpen(false)}/>}<main className={styles.chat}><header className={styles.chatHeader}><div><button className={styles.historyToggle} onClick={()=>setHistoryOpen(true)}><Menu/></button><Mark/><div><h1>{selected?.title||"Agro Assistente"}</h1><p><i/>Experiência em modo de demonstração</p></div></div><div className={styles.headerBadges}><span className={styles.demoBadge}>Demonstração</span><span className={styles.subjectBadge} data-subject={subject}>{label(subject)}</span></div></header>
  <section className={styles.messages}>{messages.length===0?<div className={styles.welcome}><Mark/><small>AGRO ASSISTENTE</small><h2>Olá, {firstName}. Como posso ajudar?</h2><p>Escolha um assunto ou descreva sua situação. Organize dúvidas sobre plantações, animais, alimentação e gestão rural.</p><div className={styles.contextCards}>{subjects.slice(1).map(item=><span key={item.value} data-subject={item.value}><item.Icon size={15}/>{item.label}</span>)}</div><div className={styles.suggestions}>{suggestions.map(item=><button data-subject={item.subject} key={item.title} onClick={()=>{setSubject(item.subject);setQuestion(item.text);textareaRef.current?.focus()}}><span><item.Icon/></span><div><strong>{item.title}</strong><small>{item.text}</small></div><ChevronRight/></button>)}</div><div className={styles.disclaimer}><AlertTriangle/><span>Orientações educativas não substituem agrônomos, médicos-veterinários ou responsáveis técnicos.</span></div></div>:messages.map(message=><article className={`${styles.message} ${styles[message.role]}`} key={message.id}><span className={styles.messageAvatar}>{message.role==="assistant"?<Mark small/>:<span>Você</span>}</span><div className={styles.bubble}><div className={styles.messageLabel}>{message.role==="assistant"?"Agro Assistente":"Você"}</div>{message.role==="assistant"?<Formatted text={message.content}/>:<div className={styles.content}>{message.content}</div>}{message.role==="assistant"&&<footer><button onClick={async()=>{await navigator.clipboard.writeText(message.content);setCopied(message.id);setTimeout(()=>setCopied(null),1500)}}>{copied===message.id?<Check/>:<Copy/>}{copied===message.id?"Copiado":"Copiar"}</button><button><ThumbsUp/></button><button><ThumbsDown/></button><small>0.8s</small></footer>}</div></article>)}{sending&&<article className={`${styles.message} ${styles.assistant}`}><span className={styles.messageAvatar}><Mark small/></span><div className={`${styles.bubble} ${styles.thinking}`}><i/><i/><i/><span>Organizando uma orientação…</span></div></article>}<div ref={endRef}/></section>
  <footer className={styles.composerArea}>{error&&<div className={styles.error}><AlertTriangle/><span>{error}</span><button onClick={()=>setError("")}><X/></button></div>}<div className={styles.quickPrompts}>{["O que devo observar?","Monte um checklist","Explique de forma simples"].map(x=><button key={x} onClick={()=>setQuestion(v=>v?v+"\n"+x:x)}>{x}</button>)}</div><div className={styles.subjects}>{subjects.map(item=><button data-subject={item.value} className={subject===item.value?styles.selectedSubject:""} onClick={()=>setSubject(item.value)} key={item.value}><item.Icon/>{item.label}</button>)}</div><form className={styles.composer} onSubmit={send}><textarea ref={textareaRef} value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Conte o que está acontecendo na sua fazenda…"/><div><small>{question.length}/4000 · Enter envia · Shift + Enter quebra a linha</small><span className={styles.composerActions}>{question&&<button className={styles.clearButton} type="button" onClick={()=>setQuestion("")}><X/></button>}<button className={styles.sendButton} disabled={!question.trim()||sending}><Send/></button></span></div></form></footer></main>
 </div>
}
